Repository tokiwa-software/fuzion, pull requests merged in 2022-11, with the labels that each got.

#572 lib: Remove 'lib/java*' and add explicit dependency to JavaObject.type
  lib/fuzion/java.fz
  lib/java.fz
  lib/java/io.fz
  lib/java/io/PrintStream.fz
  lib/java/lang.fz
  lib/java/lang/System.fz
Labels: base library

#573 fe/tools: Fix NullPointerException when 'base.fum' is missing, fix #571
  src/dev/flang/fe/FrontEndOptions.java
  src/dev/flang/tools/Fuzion.java
Labels: bug, front end

#569 Makefile: allow building without java modules
  Makefile
Labels: build infrastructure

#548 fzjava: do not generate duplicate features
  Makefile
  bin/fzjava
  src/dev/flang/fe/FrontEnd.java
  src/dev/flang/tools/Fuzion.java
  src/dev/flang/tools/FuzionHome.java
  src/dev/flang/tools/fzjava/FZJava.java
  src/dev/flang/tools/fzjava/FZJavaOptions.java
Labels: fzjava tool

#600 lib: comparableSequence.fz => comparable_sequence.fz
  lib/comparable_sequence.fz
Labels: base library, cleanup

#598 lib: fix typo in wrappingInteger and heirs
  lib/i16.fz
  lib/i32.fz
  lib/i64.fz
  lib/i8.fz
  lib/u128.fz
  lib/u16.fz
  lib/u32.fz
  lib/u64.fz
  lib/u8.fz
  lib/wrappingInteger.fz
Labels: documentation, base library, cleanup

#597 Makefile: mention that some modules from the JDK are not built
  Makefile
Labels: documentation, build infrastructure

#594 lib: rename ref types
  lib/concur/thread.fz
  lib/envir/vars.fz
  lib/exit.fz
  lib/io/err.fz
  lib/io/out.fz
  lib/io/printEffect.fz
  lib/io/stdin.fz
  lib/panic.fz
  lib/random.fz
  lib/time/nano.fz
Labels: base library, cleanup

#585 bin/run_tests.sh: be noisy, fix shellcheck issues
  bin/run_tests.sh
  bin/run_tests_parallel.sh
Labels: build infrastructure, cleanup

#445 lib: sequence.reduce, allow abort of reduction.
  lib/Sequence.fz
  lib/abort.fz
Labels: enhancement, base library

#639 lib/bitset: fix equality when one of the arguments is empty
  lib/bitset.fz
Labels: base library

#640 lib: define type.equality features for some features
  lib/bitset.fz
  lib/bool.fz
  lib/comparable_sequence.fz
  lib/complex.fz
  lib/f32.fz
  lib/f64.fz
  lib/fraction.fz
  lib/i16.fz
  lib/i32.fz
  lib/i64.fz
  lib/i8.fz
  lib/int.fz
  lib/matrix.fz
  lib/numericSequence.fz
  lib/u128.fz
  lib/u16.fz
  lib/u32.fz
  lib/u64.fz
  lib/u8.fz
  lib/uint.fz
  src/dev/flang/be/c/Intrinsics.java
  src/dev/flang/be/interpreter/Intrinsics.java
  src/dev/flang/fuir/analysis/dfa/DFA.java
  src/dev/flang/fuir/cfg/CFG.java
Labels: base library

#632 tests: fix run_tests, mod terminal
  Makefile
Labels: build infrastructure, tests

#628 lib/envir/vars: implement set and unset
  lib/envir/vars.fz
  lib/fuzion/sys/env_vars.fz
  src/dev/flang/be/c/Intrinsics.java
  src/dev/flang/fuir/analysis/dfa/DFA.java
  src/dev/flang/fuir/cfg/CFG.java
  tests/envir_vars/Makefile
  tests/envir_vars/envir_vars.fz
  tests/envir_vars/envir_vars.fz.expected_err
  tests/envir_vars/envir_vars.fz.expected_out
  tests/envir_vars/skip_int
Labels: enhancement, base library

#587 Issues/176 add regression test
  tests/reg_issue176_using_inner_field_of_boxed_outer/Makefile
  tests/reg_issue176_using_inner_field_of_boxed_outer/issue176.fz
  tests/reg_issue176_using_inner_field_of_boxed_outer/issue176.fz.expected_err
  tests/reg_issue176_using_inner_field_of_boxed_outer/issue176.fz.expected_out
Labels: C backend

#648 parser/OpExpr: adjust precedence for ≟
  src/dev/flang/parser/OpExpr.java
Labels: Fuzion language, parser

#654 lib/try: remove a leftover semicolon
  lib/try.fz
Labels: base library, cleanup

#653 Makefile: do not hardcode /bin/bash
  Makefile
Labels: build infrastructure

#652 lib: use ≟ in type.equality features
  lib/string.fz
  lib/u128.fz
  lib/uint.fz
Labels: base library, cleanup

#625 move fzdocs to the main repository
  Makefile
  assets/docs/style.css
  src/dev/flang/tools/docs/Docs.java
  src/dev/flang/tools/docs/DocsOptions.java
  src/dev/flang/tools/docs/Html.java
  src/dev/flang/tools/docs/Util.java
Labels: Fuzion tools

#663 be/c: use _Thread_local instead of __thread
  src/dev/flang/be/c/C.java
Labels: C backend

#589 Effects/delete short-hand to create and install effect
  lib/io/file/delete.fz
Labels: enhancement, base library

#603 tests: add regression test for issue 119
  tests/reg_issue119/Makefile
  tests/reg_issue119/issue119.fz
  tests/reg_issue119/issue119.fz.expected_err
  tests/reg_issue119/issue119.fz.expected_out
Labels: tests

#674 lib/tests: Replaced Type_STATIC.equality by has_equality.type.equality
  lib/Type.fz
  lib/bitset.fz
  lib/bool.fz
  lib/equals.fz
  lib/f32.fz
  lib/f64.fz
  lib/has_equality.fz
  lib/i16.fz
  lib/i32.fz
  lib/i64.fz
  lib/i8.fz
  lib/int.fz
  lib/partiallyOrdered.fz
  lib/string.fz
  lib/u128.fz
  lib/u16.fz
  lib/u32.fz
  lib/u64.fz
  lib/uint.fz
  tests/equals/test_equals.fz
  tests/equals_negative/equals_test_negative.fz
Labels: Fuzion language, base library, tests

#665 tool/util: fix duplicate stack trace
  src/dev/flang/tools/Tool.java
  src/dev/flang/util/Errors.java
Labels: fz tool

#666 tools/fzjava: when building multiple modules, separate them
  src/dev/flang/tools/fzjava/FZJava.java
  src/dev/flang/tools/fzjava/FeatureWriter.java
Labels: fzjava tool

#670 tests: remove build of MOD_JAVA_BASE from c tests
  Makefile
Labels: build infrastructure, cleanup

#680 lib: fix typo synonyme => synonym
  lib/Sequence.fz
  lib/list.fz
  lib/marray.fz
  lib/option.fz
  lib/psMap.fz
  lib/stream.fz
  lib/unit.fz
Labels: documentation, base library, cleanup

#681 lib: searchablelist0.fz => searchablelist.fz
  lib/searchablelist.fz
Labels: base library, cleanup

#682 Sequence and friends: improve documentation
  lib/Sequence.fz
  lib/array.fz
  lib/list.fz
  lib/marray.fz
  lib/searchableSequence.fz
  lib/stream.fz
Labels: documentation, base library, cleanup
