Repository tokiwa-software/fuzion, pull requests merged in 2022-12, with the labels that each got.

#688 lib/Sequence: rename forAll to for_each
  lib/Sequence.fz
  lib/array.fz
  lib/hasInterval.fz
  lib/list.fz
  lib/setOf.fz
  lib/stream.fz
  tests/choice/choicetest.fz
  tests/inheritance/inheritance.fz
  tests/rosettacode_factors_of_an_integer/factors.fz
  tests/rosettacode_primes/primes.fz
Labels: base library, cleanup

#590 Effects/move shorthand to install and create effect
  lib/io/file/move.fz
Labels: enhancement, base library

#586 `read` effect : adding short-hand to create effects
  lib/io/file/read.fz
Labels: enhancement, base library

#576 adding documentation to the operations provided by the fileio effects
  lib/fuzion/std/fileio.fz
  lib/io/file/delete.fz
  lib/io/file/move.fz
  lib/io/file/read.fz
  lib/io/file/seek.fz
  lib/io/file/stat.fz
  lib/io/file/write.fz
Labels: documentation, base library, cleanup

#750 string.substring and split: work on UTF-8 bytes rather than codepoints
  lib/string.fz
Labels: base library, cleanup

#730 lib/string: implement to_valid_utf8 features
  lib/string.fz
Labels: enhancement, base library

#732 lib/string: add find_last feature
  lib/string.fz
Labels: enhancement, base library

#751 string: rename pad_start to pad_codepoint_start
  lib/string.fz
  lib/uint.fz
Labels: documentation, base library, cleanup

#796 be/c: remove noFileIo placeholder intrinsic
  src/dev/flang/be/c/Intrinsics.java
Labels: C backend, cleanup

#797 cleanup: use new style function calls in list and string, fix a typo
  lib/fuzion/std/fileio.fz
  lib/list.fz
  lib/string.fz
Labels: base library, cleanup

#802 Tests covariance
  tests/covariance/Makefile
  tests/covariance/test_covariance.fz
  tests/covariance/test_covariance.fz.expected_err
  tests/covariance/test_covariance.fz.expected_out
Labels: tests

#758 lib/list: add prepend_to_all and intersperse features
  lib/list.fz
Labels: enhancement, base library

#799 lib: io: remove exists effect and intrinsics
  lib/fuzion/std/fileio.fz
  lib/io/file/stat.fz
  src/dev/flang/be/c/Intrinsics.java
  src/dev/flang/be/interpreter/Intrinsics.java
  src/dev/flang/fuir/analysis/dfa/DFA.java
  src/dev/flang/fuir/cfg/CFG.java
  tests/fileio/fileiotests.fz
Labels: base library, cleanup

#814 Makefile: actually replace build/tests directory
  Makefile
Labels: build infrastructure, tests

#567 lib: io.stdin, add features byte, bytes, codepoint, codepoints
  lib/codepoint.fz
  lib/io/stdin.fz
  tests/stdin/stdintest.fz
  tests/stdin/stdintest.fz.expected_out
Labels: enhancement, base library
