Repository tokiwa-software/fuzion, pull requests merged in 2023-01, with the labels that each got.

#852 lib: io: implement read_file as a fuzion feature
  lib/fuzion/std/fileio.fz
  lib/io/file/read.fz
  src/dev/flang/be/c/Intrinsics.java
  src/dev/flang/be/interpreter/Intrinsics.java
  tests/fileio/fileiotests.fz
Labels: base library

#854 lib/cache: improve documentation using better example
  lib/cache.fz
Labels: documentation, enhancement, base library

#855 lib: improve documentation for bitset, Function and int
  lib/Function.fz
  lib/bitset.fz
  lib/int.fz
Labels: documentation, enhancement, base library

#800 lib: io: implement get_file_size as a fuzion feature
  lib/fuzion/sys/fileio.fz
  src/dev/flang/be/c/Intrinsics.java
  src/dev/flang/be/interpreter/Intrinsics.java
  src/dev/flang/fuir/analysis/dfa/DFA.java
  src/dev/flang/fuir/cfg/CFG.java
Labels: base library, cleanup

#729 lib/string: add split_n, split_after, split_after_n features
  lib/String.fz
Labels: enhancement, base library

#997 air: Remove field Clazz._typeType, this information is available now
  src/dev/flang/air/Clazz.java
  src/dev/flang/air/Clazzes.java
Labels: middle end, cleanup

#998 docs: add option to show features with limited visibility
  src/dev/flang/ast/FeatureName.java
  src/dev/flang/tools/docs/Docs.java
  src/dev/flang/tools/docs/DocsOptions.java
  src/dev/flang/tools/docs/Html.java
Labels: documentation

#996 ast: Improve error created when arguments have equal names
  src/dev/flang/ast/AbstractFeature.java
  src/dev/flang/ast/AstErrors.java
  src/dev/flang/ast/Feature.java
  tests/reg_issue170_distinct_arg_names/issue170.fz.expected_err
Labels: enhancement, front end
