Repository tokiwa-software/fuzion, pull requests merged in 2024-03, with the labels that each got.

#2619 util: on contract failure try showing expression that led to failure
  Makefile
  src/dev/flang/tools/Tool.java
  src/dev/flang/util/ANY.java
  src/dev/flang/util/Version.java.in
Labels: enhancement

#2610 fe: attempt to improve readability of code of `Impl`
  src/dev/flang/ast/Feature.java
  src/dev/flang/ast/Impl.java
  src/dev/flang/ast/Loop.java
  src/dev/flang/fe/SourceModule.java
  src/dev/flang/parser/Parser.java
Labels: front end

#2604 be/c: java intrinsics
  Makefile
  include/fz.h
  include/posix.c
  include/shared.c
  include/win.c
  src/dev/flang/air/Clazzes.java
  src/dev/flang/ast/Types.java
  src/dev/flang/be/c/C.java
  src/dev/flang/be/c/CStmnt.java
  src/dev/flang/be/c/Intrinsics.java
  src/dev/flang/fuir/FUIR.java
  tests/javaBase/Makefile
  tests/javaBase/skip_c
Labels: enhancement, C backend

#2663 lib/array2: add features `transpose` and `type.create2`
  lib/array2.fz
  tests/issue2368/Makefile
  tests/issue2368/issue2368.fz
  tests/issue2368/issue2368.fz.expected_err
  tests/issue2368/issue2368.fz.expected_out
Labels: enhancement, base library

#2688 fe: fix type feature created before inheritance resolved
  src/dev/flang/ast/Call.java
  src/dev/flang/ast/Feature.java
  tests/reg_issue2687/Makefile
  tests/reg_issue2687/reg_issue2687.fz
  tests/reg_issue2687/reg_issue2687.fz.expected_err
  tests/reg_issue2687/reg_issue2687.fz.expected_out
  tests/reg_issue2687/skip_int
Labels: bug, front end

#2678 util: SourceRange, fix showInSource if start=end
  src/dev/flang/util/SourcePosition.java
Labels: bug

#2686 be/jvm: remove dependency on be/interpreter
  Makefile
  src/dev/flang/be/interpreter/JavaInterface.java
  src/dev/flang/be/jvm/runtime/Runtime.java
  src/dev/flang/util/JavaInterface.java
Labels: cleanup, jvm backend

#2723 fuir: Add caching for `FUIR.accessedClazzesDynamic`
  src/dev/flang/fuir/FUIR.java
  src/dev/flang/util/IntTriplet.java
Labels: enhancement, middle end

#2667 be/jvm: java intrinsics support exceptions
  examples/javaGraphics/gfx.fz
  lib/fuzion/java.fz
  src/dev/flang/be/jvm/Choices.java
  src/dev/flang/be/jvm/Intrinsix.java
  src/dev/flang/be/jvm/classfile/ClassFileConstants.java
  src/dev/flang/be/jvm/classfile/Expr.java
  src/dev/flang/be/jvm/runtime/Runtime.java
  src/dev/flang/tools/fzjava/ForClass.java
  tests/fz_cmd/Makefile
  tests/fz_cmd/fz_cmd.fz
  tests/fz_cmd/skip_c
  tests/javaBase/javaHello.fz
  tests/javaBase/javaHello.fz.expected_err
  tests/javaBase/javaHello.fz.expected_out
  tests/javaBase/skip_int
Labels: bug, jvm backend
