Repository tokiwa-software/fuzion, pull requests merged in 2024-11, with the labels that each got.

#4133 tests: add `name_but_not_visi_conflict`
  tests/name_but_not_visi_conflict/Makefile
  tests/name_but_not_visi_conflict/name_but_not_visi_conflict.fz
  tests/name_but_not_visi_conflict/name_but_not_visi_conflict.fz.expected_err
  tests/name_but_not_visi_conflict/name_but_not_visi_conflict.fz.expected_out
  tests/name_but_not_visi_conflict/src/a.fz
  tests/name_but_not_visi_conflict/src/b.fz
Labels: tests

#4129 ast: check effect signatures for existance of types
  lib/auto_unwrap.fz
  lib/io/buffered/reader.fz
  lib/io/file/open.fz
  lib/os/process.fz
  src/dev/flang/ast/Feature.java
  src/dev/flang/ast/Loop.java
  src/dev/flang/parser/Parser.java
Labels: front end

#4135 dfa/be: remove `fz` option `-Xdfa=on/off`
  src/dev/flang/be/c/C.java
  src/dev/flang/be/c/COptions.java
  src/dev/flang/be/jvm/JVM.java
  src/dev/flang/be/jvm/JVMOptions.java
  src/dev/flang/tools/Fuzion.java
Labels: optimizer/analyzer

#4139 tests: duplicate name, test if features can be called
  tests/name_but_not_visi_conflict/src/a.fz
  tests/name_but_not_visi_conflict/src/b.fz
Labels: tests

#4146 fix flaws in asciidoc
  src/dev/flang/fe/LibraryModule.java
  src/dev/flang/fe/LibraryOut.java
Labels: documentation

#4148 dfa: Site-insensitive analysis for non-constructors, improve #4028
  src/dev/flang/fuir/analysis/dfa/Call.java
  src/dev/flang/fuir/analysis/dfa/DFA.java
Labels: enhancement, optimizer/analyzer

#4153 dfa: catch endless recursion in Call.toString, better env debug output
  src/dev/flang/fuir/analysis/dfa/Call.java
  src/dev/flang/fuir/analysis/dfa/Env.java
Labels: enhancement, optimizer/analyzer

#4158 ast: Supress follow-up errors in jenkin's `man_or_boy2` and `tya_field` tests
  src/dev/flang/ast/AstErrors.java
  tests/choice_negative/choice_negative.fz.expected_err
  tests/reg_issue2691_b/reg_issue2691_b.fz.expected_err
  tests/visibility_negative/visibility_negative.fz.expected_err
Labels: enhancement, front end

#4144 fuir: fix Clazz.findOuter
  src/dev/flang/fuir/Clazz.java
  tests/reg_issue3567/Makefile
  tests/reg_issue3567/reg_issue3567.fz
  tests/reg_issue3567/reg_issue3567.fz.expected_err
  tests/reg_issue3567/reg_issue3567.fz.expected_out
  tests/reg_issue4143/Makefile
  tests/reg_issue4143/reg_issue4143.fz
  tests/reg_issue4143/reg_issue4143.fz.expected_err
  tests/reg_issue4143/reg_issue4143.fz.expected_out
Labels: optimizer/analyzer

#4167 fuir: cache result of `GeneratingFUIR.constClazz`
  src/dev/flang/fuir/GeneratingFUIR.java
Labels: enhancement, middle end

#4168 ast: add debug option to Resolution
  src/dev/flang/ast/Resolution.java
  src/dev/flang/util/ANY.java
Labels: enhancement, front end

#4177 dfa: Disable escape analysis during DFA for jvm/interpreter backends
  src/dev/flang/be/c/COptions.java
  src/dev/flang/fe/FrontEndOptions.java
  src/dev/flang/fuir/analysis/dfa/DFA.java
  src/dev/flang/tools/Fuzion.java
  src/dev/flang/tools/docs/Docs.java
  src/dev/flang/tools/fzjava/FZJava.java
  src/dev/flang/util/FuzionOptions.java
Labels: enhancement, optimizer/analyzer, interpreter backend, jvm backend

#4185 lib: rename String.concat1 as String.concat
  lib/String.fz
  lib/array2.fz
  lib/array3.fz
  lib/container/Set.fz
  tests/reg_issue238_array_index_out_of_bounds/issue238.fz
Labels: base library, cleanup

#4187 ast: minor cleanup in AbstractFeature.typeCall
  src/dev/flang/ast/AbstractFeature.java
Labels: front end, cleanup

#4191 ast: cleanups, change static field to instance field etc.
  README.md
  src/dev/flang/ast/AstErrors.java
  src/dev/flang/ast/Feature.java
  src/dev/flang/ast/Resolution.java
  src/dev/flang/util/Errors.java
Labels: front end, cleanup

#4178 lib: change `lock_free.map` to `lock_free.Map ref`
  lib/memoize.fz
  modules/lock_free/src/lock_free/Sieve_Cache.fz
  modules/lock_free/src/lock_free/map.fz
  tests/lib_memoize/lib_memoize.fz
  tests/mod_lock_free_Map/Makefile
  tests/mod_lock_free_Map/ctrie_test.fz
  tests/mod_lock_free_Map/ctrie_test.fz.expected_err
  tests/mod_lock_free_Map/ctrie_test.fz.expected_out
  tests/mod_lock_free_Map_threads/Makefile
  tests/mod_lock_free_Map_threads/ctrie_threads.fz
  tests/mod_lock_free_Map_threads/ctrie_threads.fz.expected_err
  tests/mod_lock_free_Map_threads/ctrie_threads.fz.expected_out
  tests/mod_lock_free_Map_threads/skip_int
  tests/reg_issue2967/reg_issue2967.fz
  tests/reg_issue3527/reg_issue3527.fz
Labels: enhancement, base library

#4212 fuir: cache results of `clazzResultClazz`, `clazzArgClazz` and `clazzArgCount`
  src/dev/flang/fuir/GeneratingFUIR.java
Labels: enhancement, middle end, performance issue

#4217 dfa: allow set field in UNIT value if field remove or of unit type, fix 4216
  src/dev/flang/fuir/analysis/dfa/DFA.java
  src/dev/flang/fuir/analysis/dfa/Value.java
Labels: bug, dfa/monomorphization

#4224 be/jvm: add invoke static for interface method
  Makefile
  src/dev/flang/be/jvm/Choices.java
  src/dev/flang/be/jvm/CodeGen.java
  src/dev/flang/be/jvm/JVM.java
  src/dev/flang/be/jvm/Types.java
  src/dev/flang/be/jvm/classfile/ClassFile.java
  src/dev/flang/be/jvm/classfile/Expr.java
Labels: cleanup, jvm backend

#4235 int: minor cleanup in code determining field size during object layout
  src/dev/flang/be/interpreter/Layout.java
Labels: interpreter backend, cleanup

#4236 c/jvm: remove Const_String from `clazzNeedsCode` in C and JVM backends
  src/dev/flang/be/c/CTypes.java
  src/dev/flang/be/jvm/Types.java
Labels: C backend, cleanup, jvm backend

#4230 ast: free types in type constraints of free types
  src/dev/flang/ast/UnresolvedType.java
  tests/reg_issue3996/Makefile
  tests/reg_issue3996/reg_issue3996.fz
  tests/reg_issue3996/reg_issue3996.fz.expected_err
  tests/reg_issue3996/reg_issue3996.fz.expected_out
Labels: front end

#4229 be/c: add more cases for native test
  src/dev/flang/be/c/C.java
  tests/native/native.fz
  tests/native/native.fz.expected_out
Labels: C backend, tests

#4244 tests: mix_inheritance_and_outer, update naming
  tests/mix_inheritance_and_outer/mix_inheritance_and_outer.fz
Labels: tests, cleanup

#4222 be/int: call native code
  src/dev/flang/be/interpreter/Executor.java
  src/dev/flang/be/interpreter/JavaInterface.java
  src/dev/flang/be/interpreter/Value.java
  src/dev/flang/be/interpreter/ValueWithClazz.java
  src/dev/flang/be/interpreter/boolValue.java
  src/dev/flang/be/interpreter/f32Value.java
  src/dev/flang/be/interpreter/f64Value.java
  src/dev/flang/be/interpreter/i16Value.java
  src/dev/flang/be/interpreter/i32Value.java
  src/dev/flang/be/interpreter/i64Value.java
  src/dev/flang/be/interpreter/i8Value.java
  src/dev/flang/be/interpreter/u16Value.java
  src/dev/flang/be/interpreter/u32Value.java
  src/dev/flang/be/interpreter/u64Value.java
  src/dev/flang/be/interpreter/u8Value.java
  tests/native/skip_int
Labels: enhancement, interpreter backend

#4258 tests: add reg test #2683
  tests/reg_issue2683/Makefile
  tests/reg_issue2683/reg_issue2683.fz
  tests/reg_issue2683/reg_issue2683.fz.expected_err
  tests/reg_issue2683/reg_issue2683.fz.expected_out
Labels: tests

#4261 ast: fix check-condition in callPostCondition
  src/dev/flang/ast/Contract.java
Labels: bug, front end

#4245 replace intrinsics nano_time/nano_sleep by native
  Makefile
  bin/fz
  lib/fuzion/std.fz
  lib/time/nano.fz
  src/dev/flang/be/c/Intrinsics.java
  src/dev/flang/be/interpreter/Intrinsics.java
  src/dev/flang/be/interpreter/u64Value.java
  src/dev/flang/be/jvm/Intrinsix.java
  src/dev/flang/be/jvm/runtime/Intrinsics.java
  src/dev/flang/fuir/analysis/dfa/DFA.java
  src/dev/flang/fuir/cfg/CFG.java
  tests/native/Makefile
Labels: enhancement, base library, backend

#4276 ast/parser: fix scoping for blocks in braces
  src/dev/flang/ast/Block.java
  src/dev/flang/parser/Parser.java
  tests/choice_negative/choice_negative.fz.expected_err
  tests/indentation_negative/indentation_negative.fz.expected_err
  tests/reg_issue2371/reg_issue2371.fz.expected_err
  tests/reg_issue2691_b/reg_issue2691_b.fz.expected_err
  tests/reg_issue3406/reg_issue3406.fz.expected_err
  tests/reg_issue3493/reg_issue3493.fz.expected_err
  tests/reg_issue3754/reg_issue3754.fz.expected_err
  tests/reg_issue4272/Makefile
  tests/reg_issue4272/reg_issue4272.fz
  tests/reg_issue4272/reg_issue4272.fz.expected_err
  tests/reg_issue4272/reg_issue4272.fz.expected_out
  tests/reg_issue627/reg_issue627.fz.expected_err
Labels: bug, parser, front end

#4280 win: fix building shared library
  .github/workflows/apple.yml
  .github/workflows/apple_c.yml
  .github/workflows/apple_int.yml
  .github/workflows/apple_jvm.yml
  .github/workflows/codeql.yml
  .github/workflows/windows.yml
  .github/workflows/windows_c.yml
  .github/workflows/windows_int.yml
  .github/workflows/windows_jvm.yml
  Makefile
  include/posix.c
  include/shared.c
Labels: github_actions, windows

#4286 ast: fix unjustfied partial ambiguity
  src/dev/flang/ast/ParsedCall.java
  tests/reg_issue3744/Makefile
  tests/reg_issue3744/reg_issue3744.fz
  tests/reg_issue3744/reg_issue3744.fz.expected_err
  tests/reg_issue3744/reg_issue3744.fz.expected_out
Labels: bug, front end

#4287 tests: add reg test #3649
  tests/reg_issue3649/Makefile
  tests/reg_issue3649/reg_issue3649.fz
  tests/reg_issue3649/reg_issue3649.fz.expected_err
  tests/reg_issue3649/reg_issue3649.fz.expected_out
Labels: tests

#4278 ast: fix false duplicate feature declaration error
  src/dev/flang/fe/SourceModule.java
  tests/reg_issue3772/Makefile
  tests/reg_issue3772/reg_issue3772.fz
  tests/reg_issue3772/reg_issue3772.fz.expected_err
  tests/reg_issue3772/reg_issue3772.fz.expected_out
Labels: bug, front end

#4274 During monomorphization, check for ambiguous result types due to ref targets and `this`-types, fix #4273
  src/dev/flang/ast/AbstractType.java
  src/dev/flang/ast/AstErrors.java
  src/dev/flang/fuir/Clazz.java
  src/dev/flang/fuir/GeneratingFUIR.java
  tests/local_mutate/test_local_mutate.fz
  tests/reg_issue4273/Makefile
  tests/reg_issue4273/reg_issue4273.fz
  tests/reg_issue4273/reg_issue4273.fz.expected_err
  tests/reg_issue4273/reg_issue4273.fz.expected_out
Labels: bug, dfa/monomorphization

#4275 be/jvm: no effect of <str> instated
  src/dev/flang/be/jvm/Intrinsix.java
  src/dev/flang/be/jvm/classfile/ClassFileConstants.java
  src/dev/flang/be/jvm/classfile/Expr.java
  src/dev/flang/be/jvm/runtime/FuzionThread.java
  src/dev/flang/be/jvm/runtime/Runtime.java
Labels: enhancement, jvm backend

#4282 be/int: fix set casefield in case result type is unittype
  src/dev/flang/be/interpreter/Executor.java
  tests/reg_issue4281/Makefile
  tests/reg_issue4281/reg_issue4281.fz
  tests/reg_issue4281/reg_issue4281.fz.expected_err
  tests/reg_issue4281/reg_issue4281.fz.expected_out
Labels: bug, interpreter backend

#4306 add_simple_test: remove workaround
  bin/add_simple_test.fz
Labels: bug, cleanup

#4311 lib: freeze arrays of array2, array3 etc.
  modules/base/src/array2.fz
  modules/base/src/array3.fz
  modules/base/src/fuzion/sys/internal_array.fz
Labels: enhancement, base library

#4319 fuir: better error output in case of cyclic value fields
  src/dev/flang/fuir/Clazz.java
  tests/choice_negative2/choice_negative.fz.expected_err
Labels: enhancement, dfa/monomorphization

#4321 ast: relax check that `finInheritanceChain` is successful
  src/dev/flang/ast/AbstractFeature.java
Labels: enhancement, front end

#4320 cosmetics: added LF
  src/dev/flang/ast/AbstractType.java
Labels: front end, cleanup

#4318 ast: petter precondition for `AbstractFeature.findInheritanceChain`
  src/dev/flang/ast/AbstractFeature.java
Labels: enhancement, front end

#4284 parser: show error for `abstract`, `intrinsic` and `native` constructors
  src/dev/flang/ast/AstErrors.java
  src/dev/flang/parser/Parser.java
  tests/reg_issue2452_abstract_constructor/Makefile
  tests/reg_issue2452_abstract_constructor/reg_issue2452_abstract_constructor.fz
  tests/reg_issue2452_abstract_constructor/reg_issue2452_abstract_constructor.fz.expected_err
  tests/reg_issue2452_abstract_constructor/reg_issue2452_abstract_constructor.fz.expected_out
Labels: Fuzion language, parser

#4326 base/net/connection: do not depend on `net.connections` effect
  modules/base/src/net/connection.fz
Labels: base library

#4327 native: replace fuzion.sys.net intriniscs by native
  include/fz.h
  include/posix.c
  include/win.c
  modules/base/src/fuzion/sys/net.fz
  modules/base/src/net/channel.fz
  modules/base/src/net/connection.fz
  modules/base/src/net/connections.fz
  modules/base/src/net/server.fz
  src/dev/flang/be/c/Intrinsics.java
  src/dev/flang/be/interpreter/Intrinsics.java
  src/dev/flang/be/jvm/runtime/Intrinsics.java
  src/dev/flang/fuir/analysis/dfa/DFA.java
  src/dev/flang/fuir/cfg/CFG.java
Labels: backend, native

#4329 ast: change outer ref names from `#^x.y` to `#^<x.y>`, fix #4316
  src/dev/flang/ast/Feature.java
  src/dev/flang/util/FuzionConstants.java
Labels: enhancement, front end

#4330 ast: avoid repeated immediate function call if resolveTypes called repeatedly
  src/dev/flang/ast/Call.java
  src/dev/flang/ast/ParsedCall.java
Labels: bug, front end

#4343 cleanup: fix typos and formatting
  Makefile
  include/shared.c
  modules/base/src/String.fz
  modules/base/src/array.fz
  modules/base/src/container/ps_map.fz
  modules/base/src/container/ps_set.fz
  modules/base/src/handles.fz
  modules/base/src/mutate.fz
  modules/base/src/time/duration.fz
  modules/base/src/uint.fz
  modules/lock_free/src/lock_free/map.fz
  src/dev/flang/ast/Feature.java
  src/dev/flang/ast/Resolution.java
  src/dev/flang/be/c/C.java
  src/dev/flang/be/interpreter/Executor.java
  src/dev/flang/be/jvm/CodeGen.java
  src/dev/flang/fuir/FUIR.java
  src/dev/flang/fuir/GeneratingFUIR.java
  src/dev/flang/fuir/analysis/dfa/DFA.java
  src/dev/flang/tools/docs/Html.java
  src/dev/flang/util/Errors.java
  tests/local_mutate/test_local_mutate.fz
  tests/simple_and_negative.mk
Labels: cleanup
