Repository tokiwa-software/fuzion, pull requests merged in 2024-12, with the labels that each got.

#4347 lib: `Sequence.sort` should require elements to be `orderable`
  modules/base/src/Sequence.fz
Labels: base library

#4345 tests: #2653, #2719, #3565
  tests/reg_issue2653/Makefile
  tests/reg_issue2653/reg_issue2653.fz
  tests/reg_issue2653/reg_issue2653.fz.expected_err
  tests/reg_issue2653/reg_issue2653.fz.expected_out
  tests/reg_issue2719/Makefile
  tests/reg_issue2719/reg_issue2719.fz
  tests/reg_issue2719/reg_issue2719.fz.expected_err
  tests/reg_issue2719/reg_issue2719.fz.expected_out
  tests/reg_issue3565/Makefile
  tests/reg_issue3565/reg_issue3565.fz
  tests/reg_issue3565/reg_issue3565.fz.expected_err
  tests/reg_issue3565/reg_issue3565.fz.expected_out
Labels: tests

#4344 tests: add reg test #1591
  tests/reg_issue1591/Makefile
  tests/reg_issue1591/reg_issue1591.fz
  tests/reg_issue1591/reg_issue1591.fz.expected_err
  tests/reg_issue1591/reg_issue1591.fz.expected_out
Labels: tests

#4341 fuir: cleanups
  src/dev/flang/fuir/GeneratingFUIR.java
Labels: cleanup, optimizer/analyzer

#4339 Makefile: fix building fuzion runtime
  Makefile
Labels: Fuzion tools, cleanup

#4338 be/int: fix toNative for i8/i16/u8/u16
  src/dev/flang/be/interpreter/ValueWithClazz.java
  src/dev/flang/be/interpreter/i16Value.java
  src/dev/flang/be/interpreter/i8Value.java
  src/dev/flang/be/interpreter/u16Value.java
  src/dev/flang/be/interpreter/u8Value.java
Labels: bug, interpreter backend

#4337 be/c: remove FILE from header file
  include/fz.h
  include/posix.c
  include/win.c
Labels: C backend, cleanup

#4336 be/jvm: cleanup, copying from/to MemorySegment from array
  src/dev/flang/be/jvm/runtime/Runtime.java
Labels: cleanup, jvm backend

#4333 ast: robustness of setActualResultType in case of errors
  src/dev/flang/ast/AbstractFeature.java
  src/dev/flang/ast/Call.java
  tests/reg_issue4332/Makefile
  tests/reg_issue4332/reg_issue4332.fz
  tests/reg_issue4332/reg_issue4332.fz.expected_err
  tests/reg_issue4332/reg_issue4332.fz.expected_out
Labels: bug, front end

#4363 makefile: run_tests_jar, fix for spaces in directory
  Makefile
Labels: bug, windows

#4361 ast: rename isFunctionType/isAnyFunctionType
  src/dev/flang/ast/AbstractType.java
  src/dev/flang/ast/Call.java
  src/dev/flang/ast/Function.java
  src/dev/flang/ast/NumLiteral.java
  src/dev/flang/ast/ParsedCall.java
  src/dev/flang/ast/Partial.java
Labels: front end, cleanup

#4300 ast: AbstractType.isRef change result type to YesNo
  src/dev/flang/ast/AbstractFeature.java
  src/dev/flang/ast/AbstractType.java
  src/dev/flang/ast/AstErrors.java
  src/dev/flang/ast/Box.java
  src/dev/flang/ast/Call.java
  src/dev/flang/ast/Expr.java
  src/dev/flang/ast/Feature.java
  src/dev/flang/ast/ResolvedNormalType.java
  src/dev/flang/ast/ResolvedParametricType.java
  src/dev/flang/ast/UnresolvedType.java
  src/dev/flang/fe/GenericType.java
  src/dev/flang/fe/LibraryFeature.java
  src/dev/flang/fe/LibraryOut.java
  src/dev/flang/fe/NormalType.java
  src/dev/flang/fuir/Clazz.java
  src/dev/flang/fuir/GeneratingFUIR.java
  src/dev/flang/util/YesNo.java
Labels: front end, cleanup

#4369 be/jvm: -jar,-classes fix `UnsupportedClassVersionError`
  Makefile
  src/dev/flang/be/jvm/JVM.java
Labels: bug, jvm backend

#4370 be/c: win.c, replace some posix code by native windows
  include/win.c
Labels: C backend, windows

#4372 parser: fix require-condition in setSourceRange
  src/dev/flang/parser/Parser.java
  tests/reg_issue4348/Makefile
  tests/reg_issue4348/reg_issue4348.fz
  tests/reg_issue4348/reg_issue4348.fz.expected_err
  tests/reg_issue4348/reg_issue4348.fz.expected_out
Labels: bug, parser

#4334 cleanup: type remove `typeOfConstant`
  bin/aspell.dict
  src/dev/flang/ast/Call.java
  src/dev/flang/ast/Constant.java
  src/dev/flang/ast/Feature.java
  src/dev/flang/ast/StrConst.java
  src/dev/flang/ast/Types.java
  src/dev/flang/be/c/C.java
  src/dev/flang/be/interpreter/Executor.java
  src/dev/flang/be/jvm/CodeGen.java
  src/dev/flang/fe/LibraryOut.java
  src/dev/flang/fuir/Clazz.java
  src/dev/flang/fuir/GeneratingFUIR.java
  src/dev/flang/fuir/analysis/dfa/Call.java
  src/dev/flang/fuir/analysis/dfa/DFA.java
Labels: front end, cleanup

#4381 fe: fix name clash of type features in different modules
  src/dev/flang/ast/AbstractFeature.java
  src/dev/flang/ast/SrcModule.java
  src/dev/flang/fe/FrontEnd.java
  src/dev/flang/fe/FrontEndOptions.java
  src/dev/flang/fe/SourceModule.java
  src/dev/flang/tools/Fuzion.java
  src/dev/flang/tools/docs/Docs.java
  src/dev/flang/tools/fzjava/FZJava.java
Labels: bug, front end

#4387 docs: replace all non-ascii in urls and paths
  src/dev/flang/tools/docs/Docs.java
  src/dev/flang/tools/docs/Html.java
Labels: bug, documentation

#4390 be/c: fix parameter 'fzouter' set but not used
  src/dev/flang/be/c/C.java
  tests/reg_issue1777/Makefile
  tests/reg_issue1777/reg_issue1777.fz
Labels: bug, C backend

#4391 lib: return Sequence instead of list
  modules/base/src/Sequence.fz
  modules/base/src/encodings/base32.fz
  modules/base/src/fuzion/sys/net.fz
  modules/base/src/list.fz
  modules/base/src/net/channel.fz
  tests/reg_issue2280/reg_issue2280.fz
  tests/reg_issue2304/reg_issue2304.fz.expected_err_int
  tests/reg_issue2304/reg_issue2304.fz.expected_err_jvm
Labels: enhancement, base library

#4392 set: -Dsun.stdout.encoding=UTF-8 -Dsun.stderr.encoding=UTF-8
  Makefile
  bin/fz
  bin/fzjava
Labels: bug, fz tool

#4396 tests: update, nested_choice_negative
  tests/nested_choice_negative/nested_choice_negative.fz
  tests/nested_choice_negative/nested_choice_negative.fz.expected_err
  tests/nested_choice_negative/skip
Labels: tests

#4397 be/effects: fix require-condition DFA.java:2659 "(v._id < 0);"
  src/dev/flang/be/effects/Effects.java
  src/dev/flang/tools/Fuzion.java
Labels: bug, dfa/monomorphization

#4393 parser: allow target of inheritance in parenthesis
  src/dev/flang/parser/Parser.java
  tests/reg_issue1641/Makefile
  tests/reg_issue1641/reg_issue1641.fz
  tests/reg_issue1641/reg_issue1641.fz.expected_err
  tests/reg_issue1641/reg_issue1641.fz.expected_out
  tests/reg_issue4348/reg_issue4348.fz.expected_err
  tests/reg_issue627/reg_issue627.fz.expected_err
Labels: bug, parser

#4394 tests: add reg test #4220
  tests/reg_issue4220/Makefile
  tests/reg_issue4220/reg_issue4220.fz
  tests/reg_issue4220/reg_issue4220.fz.expected_err
  tests/reg_issue4220/reg_issue4220.fz.expected_out
Labels: bug, tests

#4410 tests: switch #118 from fe to simple test
  tests/reg_issue118/Makefile
  tests/reg_issue118/issue118.fz.expected_err
  tests/reg_issue118/issue118.fz.expected_out
Labels: tests, cleanup

#4407 ast: fix nested tuples
  src/dev/flang/ast/ParsedCall.java
  tests/reg_issue4386/Makefile
  tests/reg_issue4386/reg_issue4386.fz
  tests/reg_issue4386/reg_issue4386.fz.expected_err
  tests/reg_issue4386/reg_issue4386.fz.expected_out
Labels: bug, front end

#4406 ast: fix type parameter constraints in pre/post features
  modules/base/src/Sequence.fz
  src/dev/flang/ast/Context.java
  src/dev/flang/ast/Contract.java
  src/dev/flang/ast/Feature.java
Labels: bug, front end

#4415 ast: fix indentation
  src/dev/flang/ast/Contract.java
Labels: cleanup

#4416 cleanup: move enum SpecialClazzes to own file
  src/dev/flang/be/c/C.java
  src/dev/flang/be/c/CTypes.java
  src/dev/flang/be/c/Intrinsics.java
  src/dev/flang/be/interpreter/Boxed.java
  src/dev/flang/be/interpreter/ChoiceIdAsRef.java
  src/dev/flang/be/interpreter/Executor.java
  src/dev/flang/be/interpreter/Instance.java
  src/dev/flang/be/interpreter/Interpreter.java
  src/dev/flang/be/interpreter/Intrinsics.java
  src/dev/flang/be/interpreter/JavaInterface.java
  src/dev/flang/be/interpreter/LValue.java
  src/dev/flang/be/interpreter/Layout.java
  src/dev/flang/be/interpreter/boolValue.java
  src/dev/flang/be/interpreter/f32Value.java
  src/dev/flang/be/interpreter/f64Value.java
  src/dev/flang/be/interpreter/i16Value.java
  src/dev/flang/be/interpreter/i32Value.java
  src/dev/flang/be/interpreter/i64Value.java
  src/dev/flang/be/interpreter/i8Value.java
  src/dev/flang/be/interpreter/u16Value.java
  src/dev/flang/be/interpreter/u32Value.java
  src/dev/flang/be/interpreter/u64Value.java
  src/dev/flang/be/interpreter/u8Value.java
  src/dev/flang/be/jvm/Choices.java
  src/dev/flang/be/jvm/CodeGen.java
  src/dev/flang/be/jvm/Intrinsix.java
  src/dev/flang/fuir/Clazz.java
  src/dev/flang/fuir/FUIR.java
  src/dev/flang/fuir/SpecialClazzes.java
  src/dev/flang/fuir/analysis/dfa/Call.java
  src/dev/flang/fuir/analysis/dfa/DFA.java
  src/dev/flang/fuir/analysis/dfa/Value.java
Labels: cleanup

#4409 ast: fix field access for select for type parameters
  src/dev/flang/ast/ParsedCall.java
  tests/reg_issue4354/Makefile
  tests/reg_issue4354/reg_issue4354.fz
  tests/reg_issue4354/reg_issue4354.fz.expected_err
  tests/reg_issue4354/reg_issue4354.fz.expected_out
Labels: bug, front end

#4417 base/net: add `ip_address` feature
  modules/base/src/net/ip_address.fz
Labels: enhancement, base library

#4432 ir: programmatically calc CLAZZ_END, SITE_BASE, etc.
  src/dev/flang/ir/IR.java
Labels: cleanup

#4433 naming: enhance naming, writeName->writeString, write->writeBytes
  src/dev/flang/fe/LibraryOut.java
  src/dev/flang/util/DataOut.java
Labels: cleanup

#4434 naming: mainClazzId -> mainClazz
  src/dev/flang/be/c/C.java
  src/dev/flang/be/interpreter/Executor.java
  src/dev/flang/be/interpreter/Interpreter.java
  src/dev/flang/be/interpreter/Intrinsics.java
  src/dev/flang/be/jvm/JVM.java
  src/dev/flang/be/jvm/Types.java
  src/dev/flang/fuir/FUIR.java
  src/dev/flang/fuir/GeneratingFUIR.java
  src/dev/flang/fuir/analysis/dfa/DFA.java
  src/dev/flang/fuir/cfg/CFG.java
Labels: cleanup

#4435 fuir: remove some debug code
  src/dev/flang/fuir/GeneratingFUIR.java
Labels: cleanup

#4438 fuir: do not add code when lookup done
  src/dev/flang/fuir/GeneratingFUIR.java
Labels: cleanup

#4437 fuir: move some abstract from GeneratingFUIR to FUIR
  src/dev/flang/fuir/FUIR.java
  src/dev/flang/fuir/GeneratingFUIR.java
Labels: cleanup

#4388 fe: allow initial value in if/else
  src/dev/flang/fe/SourceModule.java
  tests/reg_issue2483/Makefile
  tests/reg_issue2483/reg_issue2483.fz
  tests/reg_issue2483/reg_issue2483.fz.expected_err
  tests/reg_issue2483/reg_issue2483.fz.expected_out
  tests/reg_issue3901/Makefile
  tests/reg_issue3901/reg_issue3901.fz
  tests/reg_issue3901/reg_issue3901.fz.expected_err
  tests/reg_issue3901/reg_issue3901.fz.expected_out
Labels: bug, front end

#4442 ast: replace isFunctionTypeExcludingLazy by isFunctionType
  src/dev/flang/ast/AbstractType.java
  src/dev/flang/ast/Function.java
  src/dev/flang/ast/Partial.java
Labels: front end, cleanup

#4444 jvm: add Expr.trace() emitting stacktrace as comment
  src/dev/flang/be/jvm/classfile/Expr.java
Labels: enhancement, jvm backend

#4382 lib: add Sequence.count_by
  modules/base/src/Sequence.fz
  modules/base/src/list.fz
  tests/reg_issue3178/reg_issue3178.fz.expected_err_jvm
Labels: enhancement, base library

#4447 tests: add reg test #4426
  tests/reg_issue4426/Makefile
  tests/reg_issue4426/reg_issue4426.fz
  tests/reg_issue4426/reg_issue4426.fz.expected_err
  tests/reg_issue4426/reg_issue4426.fz.expected_out
Labels: tests

#4450 lib: rename Sequence.concat_sequences -> Sequence.concat
  modules/base/src/Sequence.fz
  modules/base/src/container/Mutable_Linked_List.fz
  modules/base/src/list.fz
  tests/base16/base16_test.fz
  tests/base32/base32_test.fz
  tests/base32hex/base32hex_test.fz
  tests/base64/base64_test.fz
  tests/base64url/base64url_test.fz
Labels: base library, cleanup

#4452 ast: refine isAssignableFrom checks
  src/dev/flang/ast/AbstractAssign.java
  src/dev/flang/ast/AbstractMatch.java
  src/dev/flang/ast/AbstractType.java
  src/dev/flang/ast/Call.java
  src/dev/flang/ast/Expr.java
  src/dev/flang/ast/InlineArray.java
  src/dev/flang/ast/Tag.java
  src/dev/flang/be/interpreter/Instance.java
  src/dev/flang/fe/SourceModule.java
  src/dev/flang/fuir/GeneratingFUIR.java
Labels: enhancement, front end

#4453 ast: fix result type once inferred
  src/dev/flang/ast/Feature.java
  src/dev/flang/ast/Impl.java
  tests/free_types_negative/test_free_types_negative.fz.expected_err
  tests/reg_issue2347/reg_issue2347.fz.expected_err
  tests/reg_issue4419/Makefile
  tests/reg_issue4419/reg_issue4419.fz
  tests/reg_issue4419/reg_issue4419.fz.expected_err
  tests/reg_issue4419/reg_issue4419.fz.expected_out
  tests/typeinference_for_formal_args_negative/typeinference_for_args_negative.fz.expected_err
Labels: bug, front end

#4448 ast: return null for `asType` of partialargs
  src/dev/flang/ast/Partial.java
  tests/reg_issue4420/Makefile
  tests/reg_issue4420/reg_issue4420.fz
  tests/reg_issue4420/reg_issue4420.fz.expected_err
  tests/reg_issue4420/reg_issue4420.fz.expected_out
Labels: bug, front end

#4441 fuir: move abstract methods from GenFUIR to FUIR
  src/dev/flang/be/c/C.java
  src/dev/flang/be/c/Intrinsics.java
  src/dev/flang/be/jvm/Intrinsix.java
  src/dev/flang/fuir/FUIR.java
  src/dev/flang/fuir/GeneratingFUIR.java
Labels: dfa/monomorphization, cleanup

#4459 ast: typeInferable, add comment
  src/dev/flang/ast/Impl.java
Labels: documentation, front end

#4458 `make doc`: include java docs
  Makefile
Labels: documentation, enhancement, build infrastructure

#4463 cleanup: remove isJavaRef, instanceToJavaObject
  src/dev/flang/be/c/CNames.java
  src/dev/flang/be/interpreter/Intrinsics.java
  src/dev/flang/be/interpreter/JavaInterface.java
  src/dev/flang/be/jvm/Names.java
  src/dev/flang/fuir/FUIR.java
  src/dev/flang/fuir/GeneratingFUIR.java
Labels: cleanup

#4466 base/mutate: array2: value initialization consistent with `mutate.array`
  modules/base/src/mutate/array2.fz
Labels: base library, cleanup

#4467 base/mutate: array: convenience feature for initialization
  modules/base/src/mutate/array.fz
  modules/base/src/mutate/array2.fz
Labels: enhancement, base library

#4472 be: cleanup, move unboxing to own method
  src/dev/flang/be/c/C.java
  src/dev/flang/be/interpreter/Executor.java
  src/dev/flang/be/jvm/CodeGen.java
Labels: backend, cleanup

#4474 be/jvm: cleanup NYI comment in `box`
  src/dev/flang/be/jvm/CodeGen.java
Labels: cleanup, jvm backend

#4476 base: rename `log` feature as `io.log`
  modules/base/src/io/log.fz
Labels: base library

#4475 be/c: CodeGen.call, simplify code
  src/dev/flang/be/c/C.java
Labels: C backend, cleanup

#4482 ast: do not propagate for partial if operator call in parens.
  src/dev/flang/ast/ParsedOperatorCall.java
  tests/reg_issue3659/Makefile
  tests/reg_issue3659/reg_issue3659.fz
  tests/reg_issue3659/reg_issue3659.fz.expected_err
  tests/reg_issue3659/reg_issue3659.fz.expected_out
Labels: bug, front end

#4491 cleanup: remove unused imports
  src/dev/flang/ast/AbstractCall.java
  src/dev/flang/ast/Box.java
  src/dev/flang/ast/Expr.java
  src/dev/flang/ast/Feature.java
  src/dev/flang/ast/Resolution.java
  src/dev/flang/be/effects/Effects.java
  src/dev/flang/be/interpreter/Intrinsics.java
  src/dev/flang/be/jvm/runtime/Intrinsics.java
  src/dev/flang/be/jvm/runtime/Runtime.java
  src/dev/flang/fe/LibraryFeature.java
  src/dev/flang/fe/LibraryOut.java
  src/dev/flang/util/IntMap.java
Labels: cleanup

#4487 fuir: cleanup, difference between _fields and fields()
  src/dev/flang/fuir/Clazz.java
Labels: dfa/monomorphization, cleanup

#4488 native: move fileio features to native
  include/fz.h
  include/posix.c
  include/shared.c
  include/win.c
  modules/base/src/fuzion/sys/err.fz
  modules/base/src/fuzion/sys/fileio.fz
  modules/base/src/fuzion/sys/out.fz
  modules/base/src/fuzion/sys/stdin.fz
  modules/base/src/io/dir/open.fz
  modules/base/src/io/dir/read.fz
  modules/base/src/io/dir/use.fz
  modules/base/src/io/file/mapped_buffer.fz
  modules/base/src/io/file/open.fz
  modules/base/src/io/file/seek.fz
  modules/base/src/io/file/stat.fz
  modules/base/src/io/file/use.fz
  modules/base/src/io/stdin.fz
  modules/base/src/io/stdout.fz
  src/dev/flang/be/c/Intrinsics.java
  src/dev/flang/be/interpreter/Intrinsics.java
  src/dev/flang/be/jvm/Intrinsix.java
  src/dev/flang/be/jvm/runtime/Intrinsics.java
  src/dev/flang/be/jvm/runtime/Runtime.java
  src/dev/flang/fuir/analysis/dfa/DFA.java
  src/dev/flang/fuir/cfg/CFG.java
  tests/javaBase/javaHello.fz.expected_out
  tests/lib_io_file/fileiotests.fz.expected_out
Labels: native

#4527 lib: correct result type of fzE_file_close
  modules/base/src/fuzion/sys/fileio.fz
  tests/lib_fileio_mmap/mmap_test.fz
  tests/lib_fileio_mmap/mmap_test.fz.expected_out
Labels: bug, base library, windows

#4530 lib/tests: use pipes operator in some places
  README.md
  examples/readme/example_2.fz
  modules/base/src/composition.fz
  modules/base/src/equals.fz
  modules/base/src/memoize.fz
  modules/base/src/sum.fz
  modules/base/src/transducer.fz
  modules/lock_free/src/lock_free/Sieve_Cache.fz
  tests/assignments/assignments.fz
  tests/compile_time_type_casts/compile_time_type_casts.fz
  tests/lib_fileio_mmap/mmap_test.fz
  tests/mutate_circular_buffer/ex_circular_buffer.fz
Labels: base library, tests, cleanup

#4520 fuzion java: simplify result type of array_to_java_object0
  modules/base/src/fuzion/java.fz
  src/dev/flang/be/c/Intrinsics.java
  src/dev/flang/be/interpreter/Intrinsics.java
  src/dev/flang/be/jvm/Intrinsix.java
  src/dev/flang/fuir/analysis/dfa/DFA.java
Labels: dfa/monomorphization, backend, cleanup

#4519 fuir: remove declarationPos
  src/dev/flang/be/interpreter/Executor.java
  src/dev/flang/be/interpreter/Intrinsics.java
  src/dev/flang/fuir/FUIR.java
  src/dev/flang/fuir/GeneratingFUIR.java
Labels: cleanup

#4523 lib: cleanup, move alloc, getel, setel to type features.
  modules/base/src/fuzion/sys/fileio.fz
  modules/base/src/fuzion/sys/internal_array.fz
  src/dev/flang/be/c/Intrinsics.java
  src/dev/flang/be/interpreter/Intrinsics.java
  src/dev/flang/be/jvm/Intrinsix.java
  src/dev/flang/fuir/analysis/dfa/DFA.java
  src/dev/flang/fuir/cfg/CFG.java
Labels: base library, cleanup

#4517 dfa: override accessedClazz
  src/dev/flang/fuir/analysis/AbstractInterpreter.java
  src/dev/flang/fuir/analysis/dfa/DFA.java
Labels: enhancement, dfa/monomorphization

#4526 add_simple_test: add comment explaining how to end input
  bin/add_simple_test.fz
Labels: documentation, enhancement

#4477 ai: `assignStatic` only for values that have data
  src/dev/flang/be/interpreter/Executor.java
  src/dev/flang/be/jvm/CodeGen.java
  src/dev/flang/fuir/analysis/AbstractInterpreter.java
  src/dev/flang/fuir/analysis/AbstractInterpreter2.java.patch
Labels: backend, cleanup

#4521 lib: change `Const_String` to `const_string`
  modules/base/src/const_string.fz
  modules/terminal/src/terminal.fz
  src/dev/flang/be/c/C.java
  src/dev/flang/be/c/CTypes.java
  src/dev/flang/be/c/Intrinsics.java
  src/dev/flang/be/interpreter/Executor.java
  src/dev/flang/be/interpreter/Interpreter.java
  src/dev/flang/be/interpreter/Intrinsics.java
  src/dev/flang/be/interpreter/JavaInterface.java
  src/dev/flang/be/jvm/CodeGen.java
  src/dev/flang/be/jvm/Intrinsix.java
  src/dev/flang/be/jvm/JVM.java
  src/dev/flang/be/jvm/Types.java
  src/dev/flang/be/jvm/runtime/Runtime.java
  src/dev/flang/fuir/Clazz.java
  src/dev/flang/fuir/FUIR.java
  src/dev/flang/fuir/GeneratingFUIR.java
  src/dev/flang/fuir/SpecialClazzes.java
  src/dev/flang/fuir/analysis/dfa/DFA.java
  tests/reg_issue1236/issue1236.fz.expected_out
Labels: base library, dfa/monomorphization, backend, cleanup

#4403 tests: add effects test
  Makefile
  tests/assignments/assignments.fz.effect
  tests/atomic/test_atomic.fz.effect
  tests/check_simple_example_effect.sh
  tests/compile.mk
  tests/fe.mk
  tests/hello/HelloWorld.fz.effect
  tests/i18n_default_test/i18n_default_test.fz.effect
  tests/lib_concur_sync/lib_concur_sync.fz.effect
  tests/lib_fileio_mmap/mmap_test.fz.effect
  tests/lib_io_dir/lib_io_dir.fz.effect
  tests/lib_io_file/fileiotests.fz.effect
  tests/mod_lock_free_Map/ctrie_test.fz.effect
  tests/mod_lock_free_Map_threads/ctrie_threads.fz.effect
  tests/modules/Makefile
  tests/negative.mk
  tests/record_simple_example_effect.sh
  tests/reg_issue1109/Makefile
  tests/reg_issue2237/Makefile
  tests/simple.mk
  tests/simple_and_negative.mk
  tests/simple_inp.mk
  tests/visibility_modules/Makefile
  tests/visibility_modules_negative/Makefile
Labels: tests

#4511 io: flush buffers on every say/yak etc.
  include/fz.h
  include/shared.c
  modules/base/src/fuzion/sys/err.fz
  modules/base/src/fuzion/sys/fileio.fz
  modules/base/src/fuzion/sys/out.fz
  tests/javaBase/javaHello.fz.expected_out
  tests/javaBase/javaHello.fz.expected_out_c
Labels: bug, base library

#4493 fuir: cleanup, move methods from GenFUIR to FUIR
  src/dev/flang/be/interpreter/LValue.java
  src/dev/flang/fuir/Clazz.java
  src/dev/flang/fuir/FUIR.java
  src/dev/flang/fuir/GeneratingFUIR.java
Labels: dfa/monomorphization, cleanup

#4537 spelling: UNKOWN_WORDS -> UNKNOWN_WORDS
  bin/spell_check_java.sh
Labels: cleanup

#4543 base: Add new mechanism for function memoization
  modules/base/src/memoize.fz
  tests/lib_memoize/lib_memoize.fz
  tests/lib_memoize/lib_memoize.fz.effect
  tests/lib_memoize/lib_memoize.fz.expected_out
Labels: enhancement, base library
