Repository tokiwa-software/fuzion, pull requests merged in 2025-05, with the labels that each got.

#5179 build: fix suggestion to re-run or re-record tests
  bin/run_tests.fz
Labels: bug, build infrastructure

#5178 lib: change `mutable_tree_map.type.from_array` to `.from_sequence`
  modules/base/src/container/mutable_tree_map.fz
  modules/base/src/container/ordered_map.fz
  modules/base/src/container/ps_map.fz
Labels: base library, cleanup

#5180 win: fzE_file_open fix semantics of append
  include/win.c
Labels: backend, windows

#5182 win: fix heap corruption in build_unicode_args
  include/win.c
Labels: bug, windows

#5183 run_tests: add `OS` env var to inherited env vars
  bin/run_tests.fz
Labels: build infrastructure, windows

#5184 run_tests: add `skip_win` feature
  bin/run_tests.fz
Labels: build infrastructure, windows

#5185 runtime: fzE_file_open, change arg type of mode
  include/fz.h
  include/posix.c
  include/win.c
  modules/base/src/fuzion/sys/fileio.fz
  modules/base/src/io/file/use.fz
  modules/base/src/native.fz
Labels: cleanup

#5190 cleanup: simplify precondition, add check
  src/dev/flang/ast/AbstractCall.java
  src/dev/flang/ast/AbstractCurrent.java
  src/dev/flang/ast/Partial.java
  src/dev/flang/be/jvm/CodeGen.java
  src/dev/flang/be/jvm/runtime/Runtime.java
Labels: cleanup

#5194 lib: fix casing issue (e.g. loadFence)
  modules/base/src/concur/util.fz
  src/dev/flang/be/c/Intrinsics.java
  src/dev/flang/be/interpreter/Intrinsics.java
  src/dev/flang/be/jvm/Intrinsix.java
  src/dev/flang/fuir/analysis/dfa/DFA.java
  src/dev/flang/fuir/cfg/CFG.java
Labels: cleanup

#5189 fe: AbstractType, fix NPE in applyTypePars
  src/dev/flang/ast/AbstractFeature.java
  src/dev/flang/ast/Function.java
  tests/reg_issue5188/Makefile
  tests/reg_issue5188/reg_issue5188.fz
  tests/reg_issue5188/reg_issue5188.fz.expected_err
  tests/reg_issue5188/reg_issue5188.fz.expected_out
Labels: bug, front end

#5192 docs: right align src button in api docs
  assets/docs/style.css
  src/dev/flang/tools/docs/Html.java
Labels: documentation, enhancement

#5217 ai: simplify assignStatic
  src/dev/flang/be/c/C.java
  src/dev/flang/be/interpreter/Executor.java
  src/dev/flang/be/jvm/CodeGen.java
  src/dev/flang/fuir/analysis/AbstractInterpreter.java
  src/dev/flang/fuir/analysis/AbstractInterpreter2.java.patch
  src/dev/flang/fuir/analysis/dfa/DFA.java
Labels: cleanup

#5200 lib: add uuid
  Makefile
  modules/uuid/src/uuid.fz
  tests/uuid_test/Makefile
  tests/uuid_test/uuid_test.fz
  tests/uuid_test/uuid_test.fz.expected_err
  tests/uuid_test/uuid_test.fz.expected_out
Labels: base library

#5163 fe: merge AbstractType toString/asString
  src/dev/flang/ast/AbstractCall.java
  src/dev/flang/ast/AbstractFeature.java
  src/dev/flang/ast/AbstractType.java
  src/dev/flang/ast/ArtificialBuiltInType.java
  src/dev/flang/ast/AstErrors.java
  src/dev/flang/ast/Case.java
  src/dev/flang/ast/FunctionReturnType.java
  src/dev/flang/ast/ResolvedNormalType.java
  src/dev/flang/ast/ResolvedParametricType.java
  src/dev/flang/ast/UnresolvedType.java
  src/dev/flang/fuir/Clazz.java
  src/dev/flang/fuir/FeatureAndActuals.java
  src/dev/flang/fuir/GeneratingFUIR.java
  src/dev/flang/tools/docs/Html.java
  tests/local_mutate/test_local_mutate.fz.expected_out
  tests/reg_issue2111/reg_issue2111.fz.expected_err
  tests/reg_issue2402/reg_issue2402.fz.expected_out
Labels: cleanup

#5203 ast: add check the we do do not directly assign a match to a field
  src/dev/flang/ast/AbstractAssign.java
  tests/typeinference/typeinference.fz
Labels: front end, cleanup

#5205 ast: Match, fix conflict in replacing subject field
  src/dev/flang/ast/Feature.java
  src/dev/flang/ast/Match.java
  tests/reg_issue5197/Makefile
  tests/reg_issue5197/reg_issue5197.fz
  tests/reg_issue5197/reg_issue5197.fz.expected_err
  tests/reg_issue5197/reg_issue5197.fz.expected_out
Labels: bug, front end

#5221 lib: improve error message of linear_effect
  modules/base/src/effect.fz
  tests/reg_issue4220/reg_issue4220.fz.expected_err
  tests/reg_issue4220/reg_issue4220.fz.expected_err_c
  tests/reg_issue4220/reg_issue4220.fz.expected_err_int
  tests/reg_issue4220/reg_issue4220.fz.expected_err_jvm
  tests/reg_issue4220/reg_issue4220.fz.expected_out
  tests/reg_issue4220/reg_issue4220.fz.expected_out_int
  tests/reg_issue4220/reg_issue4220.fz.expected_out_jvm
Labels: enhancement, base library

#5208 actions: add test, compile language server
  .github/workflows/apple.yml
Labels: enhancement, build infrastructure

#5206 ast: remove producesResult from `Block`
  src/dev/flang/ast/AbstractAssign.java
  src/dev/flang/ast/AbstractFeature.java
  src/dev/flang/ast/Block.java
  src/dev/flang/ast/Expr.java
  src/dev/flang/ast/Match.java
  src/dev/flang/ast/Nop.java
  tests/typeinference_negative/typeinference_negative.fz.expected_err
Labels: front end, cleanup

#5196 ast: Match, cleanup code, refine toString
  src/dev/flang/ast/Block.java
  src/dev/flang/ast/Match.java
Labels: front end, cleanup

#5212 lib: net.client mark as type feature
  modules/base/src/net/client.fz
Labels: base library, cleanup

#5215 ast: add error when calling effect.finally from user code
  src/dev/flang/ast/AstErrors.java
  src/dev/flang/ast/Call.java
  src/dev/flang/ast/Types.java
  tests/must_not_call_effect_finally/Makefile
  tests/must_not_call_effect_finally/must_not_call_effect_finally.fz
  tests/must_not_call_effect_finally/must_not_call_effect_finally.fz.expected_err
  tests/must_not_call_effect_finally/must_not_call_effect_finally.fz.expected_out
Labels: enhancement, front end

#5228 make: Add missing dependency of apidocs on fz_cmd.mod
  Makefile
Labels: bug, build infrastructure

#5216 lib: simplify circular_buffer modded_mod
  modules/base/src/mutate/circular_buffer.fz
Labels: base library, cleanup

#5207 lib: refactor thread_pool
  modules/base/src/concur/thread_pool.fz
Labels: base library, cleanup

#5226 ast: Contract, use BoolConst.TRUE/FALSE
  src/dev/flang/ast/BoolConst.java
  src/dev/flang/ast/Contract.java
Labels: front end, cleanup

#5211 lib: runtime.fault, add comment to handler args
  modules/base/src/fuzion/runtime/fault.fz
Labels: documentation, base library

#5219 lib: cleanup, concur.sync/concur.thread_pool
  modules/base/src/concur/Blocking_Queue.fz
  modules/base/src/concur/sync.fz
  modules/base/src/concur/thread_pool.fz
  modules/base/src/io/file/use.fz
Labels: base library, cleanup

#5244 lib: Fix comments in `Sequence.fz`
  modules/base/src/Sequence.fz
Labels: enhancement, cleanup

#5241 lib: Add `Sequence.infix *` to create new Sequence by repeating `n` times
  modules/base/src/Sequence.fz
Labels: enhancement, base library

#5238 scripts: remove run_tests bash scripts
  bin/run_tests.sh
  bin/run_tests_parallel.sh
Labels: build infrastructure, cleanup

#5242 lib: make Sequence.peek lazy
  modules/base/src/Sequence.fz
  tests/reg_issue5239/Makefile
  tests/reg_issue5239/reg_issue5239.fz
  tests/reg_issue5239/reg_issue5239.fz.expected_err
  tests/reg_issue5239/reg_issue5239.fz.expected_out
  tests/visibility_scoping/visibility_scoping.fz.expected_err
Labels: bug, base library

#5230 lib: circular_buffer, simplify code
  modules/base/src/mutate/circular_buffer.fz
Labels: base library, cleanup

#5247 ast: omit generics for this type in toString
  src/dev/flang/ast/AbstractType.java
  tests/reg_issue2111/reg_issue2111.fz.expected_err
Labels: enhancement, front end

#5249 lsp: remove old orphaned code
  src/dev/flang/lsp/Config.java
  src/dev/flang/lsp/FuzionLanguageServer.java
  src/dev/flang/lsp/FuzionTextDocumentService.java
  src/dev/flang/lsp/feature/InlayHints.java
  src/dev/flang/lsp/shared/QueryAST.java
  src/dev/flang/lsp/shared/SourceText.java
Labels: cleanup, lsp

#5260 lib: buffered.reader: cleanup old NYI comment
  modules/base/src/io/buffered/reader.fz
Labels: base library, cleanup

#5213 lib: net.connection, remove `is_active`
  modules/base/src/net/connection.fz
Labels: base library, cleanup

#5209 lib: use `finally` to close server
  examples/webserver/webserver_native.fz
  modules/base/src/net/server.fz
  tests/sockets/sockets_test.fz
  tests/sockets/sockets_test.fz.expected_out
  tests/sockets_thread_pool/sockets_test.fz
  tests/sockets_thread_pool/sockets_test.fz.expected_out
Labels: base library, cleanup

#5225 ast: Loop.java, improve `defaultSuccessAndElseBlocks`
  src/dev/flang/ast/Loop.java
Labels: front end, cleanup

#5222 lib/be: change thread type `i64` -> `Thread ref`
  include/fz.h
  include/posix.c
  include/shared.c
  include/win.c
  modules/base/src/concur/thread.fz
  modules/base/src/fuzion/sys/thread.fz
  modules/base/src/internal.fz
  src/dev/flang/be/interpreter/Intrinsics.java
  src/dev/flang/be/interpreter/JavaInterface.java
  src/dev/flang/be/jvm/Intrinsix.java
  src/dev/flang/be/jvm/JVM.java
  src/dev/flang/be/jvm/Types.java
  src/dev/flang/be/jvm/runtime/Intrinsics.java
  src/dev/flang/be/jvm/runtime/Runtime.java
  src/dev/flang/fuir/GeneratingFUIR.java
  src/dev/flang/fuir/SpecialClazzes.java
  src/dev/flang/fuir/analysis/dfa/DFA.java
  tests/atomic/test_atomic.fz.effect
  tests/lib_concur_sync/lib_concur_sync.fz.effect
Labels: base library, backend, cleanup

#5229 lib: add Sequence.group_by variants
  modules/base/src/Sequence.fz
  modules/lock_free/src/lock_free/group_hashable_by.fz
  tests/reg_issue238_array_index_out_of_bounds/Makefile
  tests/reg_issue238_array_index_out_of_bounds/issue238.fz.expected_out
Labels: enhancement, base library

#5218 lib: add `fzE_destroy_jvm`, turn fuzion.java into effect
  include/shared.c
  modules/base/src/fuzion/java.fz
  src/dev/flang/be/c/C.java
  src/dev/flang/be/c/Intrinsics.java
  src/dev/flang/be/interpreter/Intrinsics.java
  src/dev/flang/be/jvm/Intrinsix.java
  src/dev/flang/fuir/analysis/dfa/DFA.java
  src/dev/flang/fuir/cfg/CFG.java
  tests/javaBase/javaHello.fz
  tests/reg_issue2740/reg_issue2740.fz
  tests/reg_issue3910/reg_issue3910.fz
Labels: enhancement, base library

#5204 ast: cleanup visitation of Case/AbstractCase
  src/dev/flang/ast/AbstractCase.java
  src/dev/flang/ast/Case.java
  src/dev/flang/ast/FeatureVisitor.java
  src/dev/flang/fe/SourceModule.java
Labels: front end, cleanup

#5254 lib: unify syntax `t(arg)` => `(t arg)`
  modules/base/src/Sequence.fz
  modules/base/src/String.fz
  modules/base/src/container/abstract_array.fz
  tests/choice_mix/choice_mix.fz
  tests/choice_negative/choice_negative.fz
Labels: base library, cleanup

#5271 fix: method does not override or implement a method from a supertype
  src/dev/flang/lsp/shared/ParserTool.java
Labels: bug

#5272 tests: remove broken path in C_INCLUDE_PATH
  tests/native_value/Makefile
Labels: cleanup

#5210 lib: on cleanup error trigger runtime fault
  modules/base/src/io/dir/open.fz
  modules/base/src/io/file/mapped_buffer.fz
  modules/base/src/io/file/open.fz
  modules/base/src/net/connections.fz
Labels: enhancement, base library

#5277 tests: fz_cmd remove skip file
  tests/fz_cmd/fz_cmd.fz
  tests/fz_cmd/fz_cmd.fz.expected_err_c
  tests/fz_cmd/fz_cmd.fz.expected_out_c
  tests/fz_cmd/skip_c
  tests/record_simple_example.fz
Labels: tests, cleanup

#5274 be/c: add assert for checking size of value types are equal
  src/dev/flang/be/c/C.java
Labels: enhancement, C backend

#5273 lib: add `concur.Channel`
  modules/base/src/concur/Channel.fz
  modules/base/src/concur/Iterator.fz
  modules/base/src/concur/Receiving_Channel.fz
  modules/base/src/concur/Sending_Channel.fz
  tests/lib_concur_Channel/Makefile
  tests/lib_concur_Channel/lib_concur_Channel.fz
  tests/lib_concur_Channel/lib_concur_Channel.fz.expected_err
  tests/lib_concur_Channel/lib_concur_Channel.fz.expected_out
Labels: enhancement, base library

#5281 tests: add skip_win for fz_cmd
  tests/fz_cmd/skip_win
Labels: windows

#5267 parser: require base prefix to be repeated after dot in float literals
  src/dev/flang/parser/Lexer.java
  tests/reg_issue2386/reg_issue2386.fz.expected_err
  tests/reg_issue5199_float_base_prefix/Makefile
  tests/reg_issue5199_float_base_prefix/reg_issue5199_float_base_prefix.fz
  tests/reg_issue5199_float_base_prefix/reg_issue5199_float_base_prefix.fz.expected_err
  tests/reg_issue5199_float_base_prefix/reg_issue5199_float_base_prefix.fz.expected_out
Labels: bug, Fuzion language, parser

#5284 lib: add String.as_c_string
  examples/gtk/gtk.fz
  modules/base/src/String.fz
  modules/clang/src/clang.fz
  tests/mod_sqlite/mod_sqlite.fz
  tests/native_value/native_value.fz
Labels: base library, cleanup

#5279 lib: split fuzion.java/jvm
  examples/callingJava/javaHello.fz
  examples/javaGraphics/gfx.fz
  examples/webserver/webserver_java.fz
  include/shared.c
  modules/base/src/fuzion/java.fz
  modules/base/src/fuzion/jvm.fz
  src/dev/flang/be/c/C.java
  src/dev/flang/be/c/Intrinsics.java
  src/dev/flang/be/interpreter/Intrinsics.java
  src/dev/flang/be/interpreter/JavaInterface.java
  src/dev/flang/be/jvm/Intrinsix.java
  src/dev/flang/be/jvm/runtime/Runtime.java
  src/dev/flang/fuir/analysis/dfa/DFA.java
  src/dev/flang/fuir/cfg/CFG.java
  src/dev/flang/tools/Fuzion.java
  src/dev/flang/tools/fzjava/ForClass.java
  src/dev/flang/util/FuzionOptions.java
  tests/fz_cmd/fz_cmd.fz
  tests/javaBase/javaHello.fz
  tests/reg_issue2740/reg_issue2740.fz
  tests/reg_issue2745/reg_issue2745.fz
  tests/reg_issue2745/reg_issue2745.fz.expected_err_int
  tests/reg_issue2745/reg_issue2745.fz.expected_err_jvm
  tests/reg_issue3910/reg_issue3910.fz
Labels: base library, cleanup

#5292 cleanup: fix typos and improve formatting
  Makefile
  modules/base/src/composition.fz
  modules/base/src/memoize.fz
  modules/base/src/net/client.fz
  modules/base/src/order.fz
  src/dev/flang/fe/SourceModule.java
  tests/catch_preconditions/catch_precondition.fz
Labels: cleanup

#5289 lib: cleanup types in socket_type
  modules/base/src/net/socket_type.fz
Labels: cleanup

#5293 ast: AbstractType replace refOrVal by mode
  src/dev/flang/ast/AbstractFeature.java
  src/dev/flang/ast/AbstractType.java
  src/dev/flang/ast/AstErrors.java
  src/dev/flang/ast/Box.java
  src/dev/flang/ast/BuiltInType.java
  src/dev/flang/ast/Call.java
  src/dev/flang/ast/Expr.java
  src/dev/flang/ast/Feature.java
  src/dev/flang/ast/FreeType.java
  src/dev/flang/ast/ParsedType.java
  src/dev/flang/ast/QualThisType.java
  src/dev/flang/ast/ResolvedNormalType.java
  src/dev/flang/ast/ResolvedParametricType.java
  src/dev/flang/ast/ResolvedType.java
  src/dev/flang/ast/TypeMode.java
  src/dev/flang/ast/UnresolvedType.java
  src/dev/flang/fe/GenericType.java
  src/dev/flang/fe/LibraryFeature.java
  src/dev/flang/fe/LibraryModule.java
  src/dev/flang/fe/LibraryOut.java
  src/dev/flang/fe/NormalType.java
  src/dev/flang/fuir/Clazz.java
  src/dev/flang/fuir/GeneratingFUIR.java
  src/dev/flang/lsp/shared/TypeTool.java
  src/dev/flang/util/FuzionConstants.java
  tests/reg_issue3648/reg_issue3648.fz.expected_err
Labels: front end, cleanup
