Repository tokiwa-software/fuzion, pull requests merged in 2025-08, with the labels that each got.

#5643 lib: fix minor typo
  modules/base/src/oneway_monad.fz
Labels: documentation

#5640 make: syntaxcheck, add module terminal
  Makefile
Labels: enhancement

#5638 base: fix visibility and add comments to `state.fz`
  modules/base/src/state.fz
Labels: documentation, enhancement, base library

#5658 check_simple_example: show err/out if not okay
  tests/check_simple_example.fz
Labels: bug, Fuzion tools

#5654 lib: show error code when jvm fails to start
  include/fz.h
  include/shared.c
  modules/base/src/fuzion/jvm.fz
  src/dev/flang/be/c/Intrinsics.java
  src/dev/flang/be/interpreter/Intrinsics.java
  src/dev/flang/be/jvm/Intrinsix.java
  src/dev/flang/fuir/analysis/dfa/DFA.java
Labels: enhancement

#5663 parser: Remove `value` keyword
  src/dev/flang/parser/Lexer.java
  src/dev/flang/parser/Parser.java
Labels: enhancement, Fuzion language, parser

#5662 parser: move parsing of `...` after type to `formArgs` to match EBNF
  src/dev/flang/parser/Parser.java
Labels: enhancement, parser

#5664 lsp: add `make lsp/release`, `make build/lsp.jar`
  .github/workflows/language_server_release.yml
  README.md
  assets/Manifest.txt
  bin/fuzion_language_server
  lsp.mk
  src/dev/flang/lsp/Main.java
Labels: lsp

#5667 fe: fix explicit specification of a return type
  modules/base/src/container/abstract_array.fz
  modules/base/src/container/ordered_map.fz
  src/dev/flang/ast/Feature.java
Labels: bug

#5680 fix typos
  modules/base/src/time/Clock.fz
  modules/base/src/time/histogram.fz
  modules/base/src/time/stopwatch.fz
Labels: cleanup

#5677 fuir: cleanup remove `outer()`
  src/dev/flang/fuir/Clazz.java
Labels: dfa/monomorphization, cleanup

#5665 ast: remove unecessary code
  src/dev/flang/ast/Feature.java
Labels: front end, cleanup

#5671 fe: simplify code in `setOuterAndAddInner`
  src/dev/flang/fe/SourceModule.java
Labels: front end, cleanup

#5685 ast: Fix bug in caching of `Feature.resultTypeIfPresentUrgent`
  src/dev/flang/ast/Feature.java
Labels: front end, cleanup

#5682 add missing dependencies for `make all` to README
  README.md
Labels: documentation

#5691 bin/ebnf: make pcregrep/antlr a soft dependency
  README.md
  bin/ebnf.fz
Labels: enhancement, build infrastructure

#5693 linux, be/c: fix failure when creating jvm
  include/shared.c
Labels: bug, C backend, linux

#5696 tests: reduce flakiness of sockets test
  tests/sockets/sockets_test.fz
  tests/sockets/sockets_test.fz.expected_out
  tests/sockets_thread_pool/sockets_test.fz
  tests/sockets_thread_pool/sockets_test.fz.expected_out
Labels: enhancement, tests

#5695 lib: add atomic increment / decrement for integers
  modules/base/src/concur/atomic.fz
Labels: enhancement, base library

#5689 fe: Do not abuse feature result as type parameter constraint
  src/dev/flang/ast/AbstractFeature.java
  src/dev/flang/ast/AstErrors.java
  src/dev/flang/ast/Call.java
  src/dev/flang/ast/Feature.java
  src/dev/flang/fe/LibraryFeature.java
  src/dev/flang/fe/LibraryModule.java
  src/dev/flang/fe/LibraryOut.java
  src/dev/flang/fe/SourceModule.java
  tests/visibility_modules_negative/main.fz.expected_err
Labels: enhancement, front end, cleanup

#5701 check_simple_example, exit with failure after time limit exceeded
  tests/check_simple_example.fz
Labels: enhancement, tests, windows

#5703 makefile: add dependency to MOD_TERMINAL for target build/tests
  Makefile
Labels: bug, build infrastructure

#5706 fe: remove unused code for type address in fum file
  src/dev/flang/fe/LibraryModule.java
Labels: front end, cleanup

#5708 run_tests: record stdout/stderr in parallel instead of sequentially
  bin/run_tests.fz
Labels: enhancement

#5709 disable linter warnings on this-escape
  Makefile
Labels: build infrastructure

#5713 tests: add regression test
  tests/reg_issue5630/Makefile
  tests/reg_issue5630/reg_issue5630.fz
  tests/reg_issue5630/reg_issue5630.fz.expected_err
  tests/reg_issue5630/reg_issue5630.fz.expected_out
Labels: tests

#5710 lib: Blocking_Queue fix attempt
  modules/base/src/concur/Blocking_Queue.fz
  modules/base/src/concur/Channel.fz
  modules/base/src/concur/sync.fz
  modules/base/src/concur/thread_pool.fz
Labels: bug, base library

#5716 fe: remove unused field
  src/dev/flang/fe/SourceModule.java
Labels: cleanup

#5717 forbid defining intrinsics outside of base library
  src/dev/flang/ast/AstErrors.java
  src/dev/flang/fe/SourceModule.java
  tests/function_argument_visibility/function_argument_visibility.fz.expected_err
  tests/reg_issue5704/Makefile
  tests/reg_issue5704/reg_issue5704.fz
  tests/reg_issue5704/reg_issue5704.fz.expected_err
  tests/reg_issue5704/reg_issue5704.fz.expected_out
Labels: bug, front end

#5730 tests: update NYIs
  tests/lib_switch/lib_switch.fz
  tests/partial_application/partial_application.fz
Labels: cleanup

#5732 integrate language server release into normal release
  .github/workflows/language_server_release.yml
  Makefile
  lsp.mk
Labels: cleanup

#5681 Calling fields with open type
  modules/base/src/Values_Of_Open_Type.fz
  modules/base/src/container/Typed_Sequence.fz
  modules/base/src/tuple.fz
  src/dev/flang/ast/AbstractCall.java
  src/dev/flang/ast/AbstractFeature.java
  src/dev/flang/ast/AstErrors.java
  src/dev/flang/ast/Call.java
  src/dev/flang/ast/Feature.java
  src/dev/flang/ast/Types.java
  src/dev/flang/fe/LibraryCall.java
  src/dev/flang/fe/LibraryFeature.java
  src/dev/flang/fe/LibraryModule.java
  src/dev/flang/fe/LibraryOut.java
  src/dev/flang/fe/Module.java
  src/dev/flang/fuir/Clazz.java
  src/dev/flang/fuir/GeneratingFUIR.java
  src/dev/flang/tools/CheckIntrinsics.java
  src/dev/flang/util/FuzionConstants.java
  tests/compile_time_constants/compile_time_constants.fz.expected_out
  tests/lib_container_ps_map/lib_container_ps_map.fz.expected_out
  tests/reg_issue3168_parsing_tuples/reg_issue3168_parsing_tuples.fz.expected_out
  tests/reg_issue4386/reg_issue4386.fz.expected_out
  tests/tuple/tupletest.fz.expected_out
  tests/varargs_via_open_type_parameter/Makefile
  tests/varargs_via_open_type_parameter/varargs_via_open_type_parameter.fz
  tests/varargs_via_open_type_parameter/varargs_via_open_type_parameter.fz.expected_err
  tests/varargs_via_open_type_parameter/varargs_via_open_type_parameter.fz.expected_out
Labels: enhancement, base library, front end, middle end

#5731 tests: remove outdate NYIs visibility_negative
  tests/visibility_negative/visibility_negative.fz
Labels: tests, cleanup

#5719 tests: add reg test #5690
  tests/reg_issue5690/Makefile
  tests/reg_issue5690/reg_issue5690.fz
  tests/reg_issue5690/reg_issue5690.fz.expected_err
  tests/reg_issue5690/reg_issue5690.fz.expected_out
Labels: tests

#5744 base: Rename `list.scan` as `list.scan_list`, change result of `Sequence.scan` to `Sequence`
  modules/base/src/Sequence.fz
  modules/base/src/list.fz
Labels: enhancement, base library

#5742 add documentation for fzextract
  bin/create_tests_for_github_issues.js
  bin/fzextract.fz
Labels: cleanup

#5757 docs: fix display of type constraint in api docs
  src/dev/flang/tools/docs/Html.java
Labels: bug, documentation

#5758 fix missing curl error in jenkins
  Makefile
  README.md
  lsp.mk
Labels: bug, cleanup

#5759 lib: add feature `page_size`
  include/fz.h
  include/posix.c
  include/win.c
  modules/base/src/io/file/open.fz
  modules/base/src/native.fz
  tests/lib_fileio_mmap/mmap_test.fz
Labels: enhancement, base library

#5765 lib: add `os.cwd`
  bin/record_simple_example.fz
  include/fz.h
  include/posix.c
  include/win.c
  modules/base/src/native.fz
  modules/base/src/os/cwd.fz
  tests/lib_os_cwd/Makefile
  tests/lib_os_cwd/lib_os_cwd.fz
  tests/lib_os_cwd/lib_os_cwd.fz.expected_err
  tests/lib_os_cwd/lib_os_cwd.fz.expected_out
Labels: enhancement, base library

#5768 tests: update this_type, remove outdated NYI
  tests/this_type/test_this_type.fz
  tests/this_type/test_this_type.fz.expected_out
Labels: tests, cleanup

#5769 tests: typeinference, update old NYIs
  tests/typeinference/typeinference.fz
  tests/typeinference/typeinference.fz.expected_out
Labels: tests, cleanup

#5770 tests: add comment to native_outerref_pass_through
  tests/native_outerref_pass_through/native_outerref_pass_through.fz
  tests/native_value/fz.h
Labels: tests, cleanup

#5772 examples: Remove workaround for #5636 in examples/jitter
  examples/jitter/jitter.fz
Labels: documentation, cleanup

#5771 tests: asParsedType remove old NYI
  tests/asParsedType/test_asParsedType.fz
  tests/asParsedType/test_asParsedType.fz.expected_out
  tests/asParsedType_negative/test_asParsedType_negative.fz
Labels: tests, cleanup

#5781 base: time.histogram: improve comment to refer to period and cycle jitter
  modules/base/src/time/histogram.fz
Labels: documentation, enhancement

#5775 process: use page_size as pipe_buffer_size
  modules/base/src/os/process.fz
Labels: base library, cleanup

#5783 ast: improved error message when float literal assigned to integer
  src/dev/flang/ast/AstErrors.java
  tests/basicIntegers_negative/basicIntegers_negative.fz.expected_err
Labels: enhancement, front end

#5782 Examples jitter improvements
  examples/jitter/jitter.fz
Labels: documentation, enhancement

#5784 win: add missing include direct.h
  include/win.c
Labels: windows

#5747 lib: add percent encoding
  modules/base/src/encodings/percent.fz
  tests/percent_encoding/Makefile
  tests/percent_encoding/percent_encoding_test.fz
  tests/percent_encoding/percent_encoding_test.fz.expected_err_c
  tests/percent_encoding/percent_encoding_test.fz.expected_err_jvm
  tests/percent_encoding/percent_encoding_test.fz.expected_out_c
  tests/percent_encoding/percent_encoding_test.fz.expected_out_jvm
  tests/percent_encoding/skip_int
Labels: enhancement, base library

#5789 make: Add depencency of `build/examples` from all files `$(FZ_SRC)/examples`
  Makefile
Labels: bug, enhancement, build infrastructure

#5790 lib: io.buffered, limit read_bytes
  modules/base/src/io/buffered/reader.fz
Labels: enhancement, base library

#5794 tests: minor cleanup
  tests/reg_issue5252/reg_issue5252.fz
  tests/reg_issue5569/reg_issue5569.fz
Labels: tests, cleanup

#5807 base: Make `tuple` orderable, implemtent `type.equality` and `type.lteq`
  modules/base/src/Values_Of_Open_Type.fz
  modules/base/src/container/Typed_Sequence.fz
  modules/base/src/tuple.fz
  src/dev/flang/ast/Types.java
  src/dev/flang/fuir/GeneratingFUIR.java
  src/dev/flang/util/FuzionConstants.java
Labels: enhancement, base library

#5809 makefile: don't use slash in phony targets, make `lint-pmd` phony
  Makefile
Labels: build infrastructure, cleanup

#5817 docs: don't show non public features in inheritance or annotations
  src/dev/flang/tools/docs/Html.java
Labels: bug, documentation
