Repository tokiwa-software/fuzion, pull requests merged in 2025-09, with the labels that each got.

#5827 lib: redef Typed_Sequence.finite
  modules/base/src/container/Typed_Sequence.fz
Labels: enhancement, base library

#5830 docs: add hyperlink to constraint of type parameters
  src/dev/flang/tools/docs/Html.java
Labels: documentation, enhancement

#5837 lib: time.duration add type.hash_code
  modules/base/src/time/duration.fz
Labels: enhancement, base library

#5831 fix #1022, confusing indentation related error
  src/dev/flang/parser/Lexer.java
  tests/reg_issue1022/Makefile
  tests/reg_issue1022/reg_issue1022.fz
  tests/reg_issue1022/reg_issue1022.fz.expected_err
  tests/reg_issue1022/reg_issue1022.fz.expected_out
Labels: enhancement, parser

#5848 cleanup: use NO_CLAZZ/NO_SELECT instead of -1
  src/dev/flang/ast/AbstractCall.java
  src/dev/flang/be/jvm/Choices.java
  src/dev/flang/fe/SourceModule.java
  src/dev/flang/tools/Tool.java
Labels: cleanup

#5851 lib: add compile_time_panic
  modules/base/src/container/Set.fz
  modules/base/src/f128.fz
  modules/base/src/f16.fz
  modules/base/src/net/socket_type.fz
  modules/base/src/panic.fz
  modules/base/src/tuple.fz
Labels: enhancement, base library

#5849 lib: minor cleanup in processes
  modules/base/src/os/processes.fz
Labels: base library, cleanup

#5838 fe: fix inheriting from feature with open type parameters
  src/dev/flang/ast/AbstractCall.java
  src/dev/flang/ast/AstErrors.java
  src/dev/flang/ast/Call.java
  src/dev/flang/util/List.java
  tests/reg_issues5821_5835/Makefile
  tests/reg_issues5821_5835/reg_issues5821_5835.fz
  tests/reg_issues5821_5835/reg_issues5821_5835.fz.expected_err
  tests/reg_issues5821_5835/reg_issues5821_5835.fz.expected_out
Labels: bug, front end

#5858 docs: profiling add section for java flight recorder
  doc/profiling_fuzion.adoc
Labels: documentation, enhancement

#5834 ast: ContextVisitor move condition logic to own method
  src/dev/flang/ast/ContextVisitor.java
Labels: front end, cleanup

#5859 lib: fix soundness issue
  modules/base/src/time/Clock.fz
Labels: bug, base library

#5860 lib: change visbilities of handles(2)/bitset
  modules/base/src/bitset.fz
  modules/base/src/handles.fz
  modules/base/src/handles2.fz
Labels: base library, cleanup

#5863 Makefile: compile `run_tests.fz` in a separate target
  Makefile
Labels: build infrastructure, cleanup

#5870 allow code in universe comment
  modules/base/src/universe.fz
  src/dev/flang/tools/docs/Util.java
Labels: documentation

#5862 lib: process.wait add timeout parameter
  bin/run_tests.fz
  include/posix.c
  include/win.c
  modules/base/src/native.fz
  modules/base/src/os/process.fz
  modules/base/src/os/processes.fz
Labels: enhancement, base library

#5869 lib: improve comment in bitset
  modules/base/src/bitset.fz
Labels: base library, cleanup

#5855 fe: fix check condition failure in man_or_boy2
  src/dev/flang/ast/Function.java
  tests/reg_issue5854/Makefile
  tests/reg_issue5854/reg_issue5854.fz
  tests/reg_issue5854/reg_issue5854.fz.expected_err
  tests/reg_issue5854/reg_issue5854.fz.expected_out
Labels: bug, front end

#5873 Makefile: fix error caused by missing directory `build/include/`
  Makefile
Labels: bug, build infrastructure

#5876 timer: split dfa into dfa1 and dfa2
  src/dev/flang/fuir/analysis/dfa/DFA.java
  src/dev/flang/tools/Fuzion.java
Labels: enhancement

#5880 win: fix hang in sleep, don't use WaitForSingleObject with 0 timeout
  include/win.c
Labels: bug, windows

#5877 util: Show failing pre/post/check condition even if it comes from generated code
  src/dev/flang/tools/Fuzion.java
  src/dev/flang/util/ANY.java
Labels: enhancement, Fuzion tools, cleanup

#5887 base: add `frequency.as_string`
  modules/base/src/time/frequency.fz
Labels: enhancement, base library

#5898 base: refine preconditions for ordered/hash map
  modules/base/src/container/hash_map.fz
  modules/base/src/container/ordered_map.fz
Labels: enhancement, base library

#5901 be/jvm: add missing space in error string
  src/dev/flang/be/jvm/runtime/Runtime.java
Labels: enhancement

#5897 base: Add `Typed_Sequence.variadic`, minor cleanup
  modules/base/src/container/Typed_Sequence.fz
Labels: enhancement, base library

#5906 fuir: remove special clazz `c_Array`
  src/dev/flang/be/c/C.java
  src/dev/flang/be/interpreter/ArrayData.java
  src/dev/flang/be/interpreter/ChoiceIdAsRef.java
  src/dev/flang/be/interpreter/Executor.java
  src/dev/flang/be/interpreter/Interpreter.java
  src/dev/flang/be/interpreter/Intrinsics.java
  src/dev/flang/be/interpreter/JavaInterface.java
  src/dev/flang/be/jvm/Intrinsix.java
  src/dev/flang/fuir/GeneratingFUIR.java
  src/dev/flang/fuir/SpecialClazzes.java
Labels: bug, dfa/monomorphization, interpreter backend

#5908 mod: get rid of parens `))))`
  modules/lock_free/src/lock_free/Map.fz
  modules/uuid/src/uuid.fz
Labels: base library, cleanup

#5909 modules: code readability improvements
  modules/base/src/String.fz
  modules/base/src/container/hash_map.fz
  modules/base/src/os/processes.fz
  modules/http/src/http/canonical_header_map.fz
  modules/lock_free/src/lock_free/Map.fz
  modules/nom/src/nom/multi.fz
  modules/nom/src/nom/parsers/json.fz
Labels: base library, cleanup

#5911 include: fix incogruence fz.h / shared.c
  include/fz.h
  include/shared.c
Labels: bug, C backend

#5914 ast: do not use `whenResolvedTypes` in `resolveFormalArgumentTypes`
  src/dev/flang/ast/AbstractCall.java
  src/dev/flang/ast/Call.java
Labels: front end, cleanup

#5917 ast: fix AbstractFeature.toString when very early in frontend
  src/dev/flang/ast/AbstractFeature.java
Labels: bug, front end

#5948 ast: remove error `Formal type parameter must not be outer type`, cleanup
  src/dev/flang/ast/AstErrors.java
  src/dev/flang/ast/UnresolvedType.java
Labels: front end, cleanup

#5944 ast/fuir: Fix using open type parameters in inherited feature
  src/dev/flang/ast/AbstractFeature.java
  src/dev/flang/fuir/Clazz.java
  tests/reg_issue5941/Makefile
  tests/reg_issue5941/reg_issue5941.fz
  tests/reg_issue5941/reg_issue5941.fz.expected_err
  tests/reg_issue5941/reg_issue5941.fz.expected_out
Labels: bug, front end, middle end

#5924 ast: cleanup: fix comment with outdated Fuzion lambda syntax
  src/dev/flang/ast/Feature.java
Labels: front end, cleanup

#5956 lib: fix slice of slice by redefining slice in arrayslice
  modules/base/src/container/abstract_array.fz
Labels: bug, base library

#5959 lib: exanding_array, fix comment
  modules/base/src/container/expanding_array.fz
Labels: documentation, cleanup

#5965 fuir: use Bitset for _accessedSites
  src/dev/flang/fuir/GeneratingFUIR.java
  src/dev/flang/fuir/OptimizedFUIR.java
Labels: dfa/monomorphization, performance issue

#5962 ast: fix open type parameters inherited from type parameter constraints
  src/dev/flang/ast/AbstractCall.java
  src/dev/flang/ast/AbstractType.java
  src/dev/flang/fuir/GeneratingFUIR.java
  tests/reg_issue5895/reg_issue5895.fz
  tests/reg_issue5895/reg_issue5895.fz.expected_out
Labels: bug, front end

#5951 lib: implement array_slice as an abstract_array
  modules/base/src/container/abstract_array.fz
Labels: base library, cleanup, performance issue

#5972 lib: extend Sequence.split_at
  modules/base/src/Sequence.fz
  tests/sequence/sequence.fz
  tests/sequence/sequence.fz.expected_out
Labels: enhancement, base library

#5945 http: simplify code, remove canonical header map
  modules/http/src/http.fz
  modules/http/src/http/Message.fz
  modules/http/src/http/canonical_header_map.fz
  modules/http/src/http/constants.fz
  modules/http/src/http/request_msg.fz
  modules/http/src/http/request_reader.fz
  modules/http/src/http/response_msg.fz
  modules/http/src/http/response_reader.fz
  modules/http/src/http/util.fz
  tests/mod_http_message/http_message_test.fz
Labels: base library, cleanup

#5983 lib: Sequence, do find/replace on array backed Sequences
  modules/base/src/Sequence/equatable.fz
Labels: base library, performance issue

#5990 ast: cleanup in `inferGenericLambdaResult`: avoid `boolean[] result` argument
  src/dev/flang/ast/Call.java
Labels: front end, cleanup

#5994 ast: add support to infer partial and lambda from type parameter constraint
  src/dev/flang/ast/AbstractFeature.java
  src/dev/flang/ast/Call.java
  src/dev/flang/ast/Feature.java
  tests/reg_issue5987/Makefile
  tests/reg_issue5987/reg_issue5987.fz
  tests/reg_issue5987/reg_issue5987.fz.expected_err
  tests/reg_issue5987/reg_issue5987.fz.expected_out
Labels: enhancement, front end

#6020 base: fix calls to `as_codepoints` which must be `codepoints`
  modules/base/src/String.fz
Labels: bug, base library

#6019 run_tests: histogram, add arg max_recorded
  bin/run_tests.fz
Labels: enhancement, tests
