Repository tokiwa-software/fuzion, pull requests merged in 2025-07, with the labels that each got.

#5367 lib: add means to compose effects more easily
  modules/base/src/Functional.fz
  modules/base/src/effect.fz
  modules/base/src/net/connection.fz
Labels: enhancement, base library

#5448 ebnf: raise error on grammar error
  bin/ebnf.fz
  src/dev/flang/parser/Lexer.java
Labels: bug, enhancement

#5445 ast: add, `ThisType` has no generics and no outer
  src/dev/flang/ast/AbstractFeature.java
  src/dev/flang/ast/AbstractType.java
  src/dev/flang/ast/Call.java
  src/dev/flang/ast/Case.java
  src/dev/flang/ast/Expr.java
  src/dev/flang/ast/ResolvedNormalType.java
  src/dev/flang/ast/ThisType.java
  src/dev/flang/ast/UnresolvedType.java
  src/dev/flang/fe/LibraryModule.java
  src/dev/flang/fe/LibraryOut.java
  src/dev/flang/fe/NormalType.java
  src/dev/flang/fe/ThisType.java
  tests/reg_issue1666/reg_issue1666.fz.expected_err
Labels: front end, cleanup

#5458 lib: partially revert #3963
  modules/base/src/container/ordered_map.fz
Labels: base library, cleanup

#5459 ast: fix resolveFormalArg for open generics that have to be extracted…
  src/dev/flang/ast/AbstractCall.java
  tests/reg_issue5433/Makefile
  tests/reg_issue5433/reg_issue5433.fz
  tests/reg_issue5433/reg_issue5433.fz.expected_err
  tests/reg_issue5433/reg_issue5433.fz.expected_out
Labels: bug, front end

#5455 fix partial application for block without result expression
  src/dev/flang/ast/AbstractBlock.java
  src/dev/flang/ast/Call.java
  src/dev/flang/ast/Constant.java
  src/dev/flang/ast/Expr.java
  src/dev/flang/ast/Feature.java
  tests/nested_lazy/ex_nested_lazy.fz.expected_err
  tests/reg_issue5352/Makefile
  tests/reg_issue5352/reg_issue5352.fz
  tests/reg_issue5352/reg_issue5352.fz.expected_err
  tests/reg_issue5352/reg_issue5352.fz.expected_out
Labels: bug, front end

#5478 ast: cleanup AbstractType asValue/asRef/asThis
  src/dev/flang/ast/AbstractType.java
  src/dev/flang/ast/AstErrors.java
  src/dev/flang/ast/ParsedType.java
  src/dev/flang/ast/ResolvedNormalType.java
  src/dev/flang/ast/ResolvedParametricType.java
  src/dev/flang/ast/ThisType.java
  src/dev/flang/ast/UnresolvedType.java
  src/dev/flang/fe/GenericType.java
  src/dev/flang/fe/NormalType.java
  src/dev/flang/fe/ThisType.java
  src/dev/flang/fuir/Clazz.java
Labels: front end, cleanup

#5476 be/jvm: add error message for missing library
  src/dev/flang/be/jvm/runtime/Runtime.java
Labels: enhancement, jvm backend

#5486 ast: merge targetType hacks
  src/dev/flang/ast/Call.java
Labels: front end, cleanup

#5487 ast: resolveSelect move setToErrorState to end
  src/dev/flang/ast/Call.java
Labels: cleanup

#5461 remove second iteration in handDown
  src/dev/flang/ast/AbstractType.java
  src/dev/flang/fuir/Clazz.java
  src/dev/flang/fuir/GeneratingFUIR.java
Labels: cleanup

#5496 base: fix and improve comments for `Type.infix :`.
  modules/base/src/Type.fz
Labels: documentation, enhancement, base library

#5498 ast: loop add support for loop invariants
  modules/base/src/fuzion/runtime/invariant_fault.fz
  src/dev/flang/ast/Check.java
  src/dev/flang/ast/Contract.java
  src/dev/flang/ast/Loop.java
  src/dev/flang/parser/Parser.java
  tests/loop_invariant/Makefile
  tests/loop_invariant/loop_invariant.fz
  tests/loop_invariant/loop_invariant.fz.expected_err_c
  tests/loop_invariant/loop_invariant.fz.expected_err_int
  tests/loop_invariant/loop_invariant.fz.expected_err_jvm
  tests/loop_invariant/loop_invariant.fz.expected_out_c
  tests/loop_invariant/loop_invariant.fz.expected_out_int
  tests/loop_invariant/loop_invariant.fz.expected_out_jvm
Labels: enhancement, Fuzion language

#5506 remove unused constant
  src/dev/flang/util/FuzionConstants.java
Labels: cleanup

#5507 ast: cleanup Feature constructor
  src/dev/flang/ast/Feature.java
Labels: cleanup

#5512 lsp.mk: do not rebuild lsp completely every time
  lsp.mk
Labels: build infrastructure, lsp

#5395 cleanup: move boxing/tagging to IR
  src/dev/flang/ast/AbstractAssign.java
  src/dev/flang/ast/AbstractBlock.java
  src/dev/flang/ast/AbstractCall.java
  src/dev/flang/ast/AbstractType.java
  src/dev/flang/ast/Block.java
  src/dev/flang/ast/Call.java
  src/dev/flang/ast/Expr.java
  src/dev/flang/ast/Feature.java
  src/dev/flang/ast/FeatureVisitor.java
  src/dev/flang/ast/InlineArray.java
  src/dev/flang/ast/ParsedType.java
  src/dev/flang/ast/Resolution.java
  src/dev/flang/ast/State.java
  src/dev/flang/ast/UnresolvedType.java
  src/dev/flang/fe/LibraryFeature.java
  src/dev/flang/fe/LibraryOut.java
  src/dev/flang/fuir/GeneratingFUIR.java
  src/dev/flang/ir/Box.java
  src/dev/flang/ir/IR.java
  src/dev/flang/ir/Tag.java
  src/dev/flang/lsp/shared/ASTWalker.java
  src/dev/flang/lsp/shared/CallTool.java
  src/dev/flang/lsp/shared/ParserTool.java
  tests/choice_negative/choice_negative.fz.expected_err
  tests/reg_issue1518/reg_issue1518.fz.expected_err
  tests/reg_issue2347/reg_issue2347.fz.expected_err
  tests/reg_issue5268/reg_issue5268.fz.expected_err
Labels: front end, dfa/monomorphization, cleanup

#5521 ast: move logic to of extracting typeParType to `asTypeParameterType`
  src/dev/flang/ast/AbstractCall.java
  src/dev/flang/ast/AbstractType.java
  src/dev/flang/ast/Expr.java
Labels: cleanup

#5519 merge actualArgType, adjustResultType
  src/dev/flang/ast/AbstractCall.java
  src/dev/flang/ast/Call.java
Labels: front end, cleanup

#5525 fe: move cotype() from Feature to Resolution
  src/dev/flang/ast/AbstractFeature.java
  src/dev/flang/ast/AbstractType.java
  src/dev/flang/ast/Call.java
  src/dev/flang/ast/Feature.java
  src/dev/flang/ast/Resolution.java
  src/dev/flang/fe/SourceModule.java
Labels: cleanup

#5524 cleanup: use NO_CLAZZ instead of -1
  src/dev/flang/be/c/C.java
  src/dev/flang/be/c/CNames.java
  src/dev/flang/be/c/Intrinsics.java
  src/dev/flang/be/interpreter/Executor.java
  src/dev/flang/be/interpreter/FuzionThread.java
  src/dev/flang/be/jvm/CodeGen.java
  src/dev/flang/be/jvm/JVM.java
  src/dev/flang/be/jvm/Names.java
  src/dev/flang/be/jvm/Types.java
  src/dev/flang/fuir/DfaFUIR.java
  src/dev/flang/fuir/analysis/dfa/ValueSet.java
Labels: cleanup

#5528 ast: add comment and rename `_unresolvedGenerics`
  src/dev/flang/ast/Call.java
Labels: cleanup

#5531 call: ensure target/actuals/actualTypeParameters are not null
  src/dev/flang/ast/AbstractCall.java
  src/dev/flang/ast/Call.java
  src/dev/flang/ast/ParsedCall.java
  src/dev/flang/fe/SourceModule.java
Labels: cleanup

#5535 ast: move FormalGenerics.resolve to Resolution
  src/dev/flang/ast/AbstractFeature.java
  src/dev/flang/ast/Call.java
  src/dev/flang/ast/FormalGenerics.java
  src/dev/flang/ast/Resolution.java
  src/dev/flang/ast/UnresolvedType.java
Labels: cleanup

#5537 ast: formalgenerics, transparently use type args of feature
  src/dev/flang/ast/AbstractFeature.java
  src/dev/flang/ast/AbstractType.java
  src/dev/flang/ast/AstErrors.java
  src/dev/flang/ast/Call.java
  src/dev/flang/ast/Case.java
  src/dev/flang/ast/Context.java
  src/dev/flang/ast/Feature.java
  src/dev/flang/ast/FormalGenerics.java
  src/dev/flang/fe/FeErrors.java
  src/dev/flang/fe/LibraryModule.java
  src/dev/flang/fe/LibraryOut.java
  src/dev/flang/fe/SourceModule.java
  src/dev/flang/lsp/shared/TypeTool.java
Labels: cleanup

#5552 remove some unused code, refine visibility/modifiers
  src/dev/flang/ast/AbstractAssign.java
  src/dev/flang/ast/AbstractBlock.java
  src/dev/flang/ast/AbstractCall.java
  src/dev/flang/ast/AbstractCase.java
  src/dev/flang/ast/AbstractFeature.java
  src/dev/flang/ast/AbstractMatch.java
  src/dev/flang/ast/Expr.java
  src/dev/flang/ast/ExpressionVisitor.java
  src/dev/flang/ast/InlineArray.java
  src/dev/flang/ast/SrcModule.java
  src/dev/flang/fe/LibraryOut.java
  src/dev/flang/fe/Module.java
  src/dev/flang/fuir/analysis/dfa/Env.java
  src/dev/flang/ir/Box.java
  src/dev/flang/ir/Tag.java
Labels: cleanup

#5557 ast: change AbstractFeature.toString
  src/dev/flang/ast/AbstractFeature.java
  tests/reg_issue1666/reg_issue1666.fz.expected_err
Labels: enhancement

#5559 tests: make `tests/free_types_negative` _simple_and_negative_
  tests/free_types_negative/Makefile
Labels: enhancement, tests

#4322 tests: in `negative.fz` use `$(FILE)` instead of `$(NAME)`
  tests/negative.mk
  tests/reg_issue4273/reg_issue4273.fz
  tests/reg_issue4273/reg_issue4273.fz.expected_err
  tests/simple_and_negative.mk
Labels: build infrastructure, tests

#5565 ast: remove resolve one arg (moreThanTypes)
  src/dev/flang/ast/InlineArray.java
  src/dev/flang/ast/Match.java
  src/dev/flang/ast/Resolution.java
Labels: cleanup

#5554 ast: make sure freetypes are split off when creating cotype
  src/dev/flang/ast/Call.java
  src/dev/flang/ast/Resolution.java
Labels: enhancement

#5576 ast: change visibility of AbstractFeature.state from public to package
  src/dev/flang/ast/AbstractFeature.java
  src/dev/flang/fe/Module.java
  src/dev/flang/fe/SourceModule.java
Labels: cleanup

#5574 ast: cleanups in formal generics
  src/dev/flang/ast/AbstractFeature.java
  src/dev/flang/ast/AstErrors.java
  src/dev/flang/ast/FormalGenerics.java
  src/dev/flang/lsp/shared/FeatureTool.java
  src/dev/flang/lsp/shared/TypeTool.java
Labels: cleanup

#5579 ast: Case, don't visit _types
  src/dev/flang/ast/Case.java
Labels: cleanup

#5581 ast: enable precondition for matching generic sizes
  src/dev/flang/ast/ResolvedNormalType.java
  src/dev/flang/ast/UnresolvedType.java
Labels: cleanup

#5582 ast: call remove seemingly unecessary resolve of generics
  src/dev/flang/ast/Call.java
Labels: cleanup

#5587 ast, replaceGenericsAndOuter: stricter pre condition
  src/dev/flang/ast/AbstractType.java
Labels: enhancement

#5586 ast: resultTypeIfPresentUrgent, resolve outer on incomplete type
  src/dev/flang/ast/AbstractType.java
  src/dev/flang/ast/Case.java
  src/dev/flang/ast/Feature.java
  src/dev/flang/ast/FunctionReturnType.java
  src/dev/flang/ast/IncompleteType.java
  src/dev/flang/ast/ReturnType.java
  src/dev/flang/ast/UnresolvedType.java
Labels: bug, front end

#5591 ast/fe/fuir: cleanup: resolved types are not a concept for the middle end
  src/dev/flang/ast/AbstractType.java
  src/dev/flang/ast/ResolvedNormalType.java
  src/dev/flang/fe/NormalType.java
  src/dev/flang/fuir/Clazz.java
Labels: front end, dfa/monomorphization, cleanup

#5607 ast: Fix `NullPointerException` in `Universe.typeforInferencing`
  src/dev/flang/ast/Universe.java
Labels: bug, front end

#5601 revert cfe45d7, since this does not work on windows
  tests/modules/b.make
Labels: bug, windows

#5599 ast: simplify if/else code
  src/dev/flang/ast/This.java
Labels: cleanup

#5605 Simplify needs boxing logic
  src/dev/flang/ast/Expr.java
Labels: cleanup

#5614 fix reading uninitialized field
  src/dev/flang/fuir/analysis/dfa/Instance.java
  tests/reg_issue5085/Makefile
  tests/reg_issue5085/reg_issue5085.fz
  tests/reg_issue5085/reg_issue5085.fz.expected_err
  tests/reg_issue5085/reg_issue5085.fz.expected_out
Labels: bug, dfa/monomorphization

#5612 ast: remove unused code `resolveGenerics`
  src/dev/flang/ast/AbstractType.java
Labels: cleanup

#5616 ast: fix #5353, require condition in Call
  src/dev/flang/ast/Feature.java
  src/dev/flang/ast/Match.java
  tests/reg_issue5353/Makefile
  tests/reg_issue5353/reg_issue5353.fz
  tests/reg_issue5353/reg_issue5353.fz.expected_err
  tests/reg_issue5353/reg_issue5353.fz.expected_out
Labels: bug, front end

#5621 lib: remove outdated NYI in `mutate`
  modules/base/src/mutate.fz
  tests/reg_issue3352/reg_issue3352.fz.expected_err_int
  tests/reg_issues455-456_dot_type/dot_type_test.fz
Labels: cleanup

#5625 base: fix minor typo in comment
  modules/base/src/exception.fz
Labels: documentation, enhancement

#5628 add workaround for windows encoding issue
  modules/base/src/fuzion/jvm.fz
  tests/fz_cmd/fz_cmd.fz
  tests/javaBase/javaHello.fz
Labels: bug, windows

#5629 http: change visibility of `canonical_header_map.map_of`
  modules/http/src/http/canonical_header_map.fz
Labels: enhancement
