Repository tokiwa-software/fuzion, pull requests merged in 2025-04, with the labels that each got.

#4981 ast: extend syntax sugar to convert numliterals to required type
  src/dev/flang/ast/Constant.java
  src/dev/flang/ast/Feature.java
  src/dev/flang/ast/FeatureVisitor.java
  src/dev/flang/ast/NumLiteral.java
  tests/numliteral_syntax_sugar_issue4754/Makefile
  tests/numliteral_syntax_sugar_issue4754/numliteral_syntax_sugar_issue4754.fz
  tests/numliteral_syntax_sugar_issue4754/numliteral_syntax_sugar_issue4754.fz.expected_err
  tests/numliteral_syntax_sugar_issue4754/numliteral_syntax_sugar_issue4754.fz.expected_out
Labels: enhancement, front end

#4986 ast: avoid errors caused by additional lambda argument
  src/dev/flang/ast/Call.java
  src/dev/flang/ast/Feature.java
  src/dev/flang/ast/Function.java
  tests/reg_issue4457/Makefile
  tests/reg_issue4457/reg_issue4457.fz
  tests/reg_issue4457/reg_issue4457.fz.expected_err
  tests/reg_issue4457/reg_issue4457.fz.expected_out
Labels: enhancement, front end

#5000 Fix 4992: Type constraint using`.this` results in error
  src/dev/flang/ast/AbstractType.java
  src/dev/flang/ast/Call.java
  tests/reg_issue4992/Makefile
  tests/reg_issue4992/reg_issue4992.fz
  tests/reg_issue4992/reg_issue4992.fz.expected_err
  tests/reg_issue4992/reg_issue4992.fz.expected_out
  tests/reg_issues4992_5001_negative/Makefile
  tests/reg_issues4992_5001_negative/reg_issues4992_5001_negative.fz
  tests/reg_issues4992_5001_negative/reg_issues4992_5001_negative.fz.expected_err
  tests/reg_issues4992_5001_negative/reg_issues4992_5001_negative.fz.expected_out
Labels: bug, front end

#5004 lib: fix argument order inconsistency in `scan` and `fold` in `Sequence`
  modules/base/src/Sequence.fz
  modules/base/src/encodings/base32.fz
  modules/base/src/list.fz
  tests/partial_application_negative/partial_application_negative.fz.expected_err
Labels: base library, cleanup

#5005 ast: Fix position of inheritance calls generated for cotype, fix #5003
  src/dev/flang/ast/AbstractCall.java
  src/dev/flang/ast/AbstractFeature.java
  tests/reg_issue5003/Makefile
  tests/reg_issue5003/reg_issue5003.fz
  tests/reg_issue5003/reg_issue5003.fz.expected_err
  tests/reg_issue5003/reg_issue5003.fz.expected_out
Labels: bug, front end

#5013 tests: process_utf8, move target all to beginning
  tests/process_utf8/Makefile
Labels: tests, cleanup

#5009 ast: add impl. restriction error for unsupported contracts
  src/dev/flang/ast/Contract.java
  tests/reg_issue3493/reg_issue3493.fz.expected_err
Labels: front end

#5011 be/jvm: change type of functions descriptor args array
  src/dev/flang/be/jvm/JVM.java
Labels: enhancement, jvm backend

#5012 fuir: clazzOuterRef, always return NO_CLAZZ for native, fields etc.
  src/dev/flang/fuir/GeneratingFUIR.java
  src/dev/flang/ir/IR.java
Labels: dfa/monomorphization

#5020 ast: fix inference of lambda with no arguments
  src/dev/flang/ast/Call.java
  src/dev/flang/ast/Function.java
  src/dev/flang/ast/InlineArray.java
  src/dev/flang/ast/ResolvedNormalType.java
  src/dev/flang/ast/Types.java
  tests/reg_issue5018/Makefile
  tests/reg_issue5018/reg_issue5018.fz
  tests/reg_issue5018/reg_issue5018.fz.expected_err
  tests/reg_issue5018/reg_issue5018.fz.expected_out
  tests/reg_issue929/reg_issue929.fz.expected_err
Labels: bug, front end

#5021 be/c/jvm: add initial support for native values
  .github/workflows/apple.yml
  .github/workflows/linux.yml
  Makefile
  bin/fzextract.fz
  modules/clang/src/clang.fz
  src/dev/flang/ast/AbstractFeature.java
  src/dev/flang/ast/Feature.java
  src/dev/flang/be/c/C.java
  src/dev/flang/be/jvm/CodeGen.java
  src/dev/flang/be/jvm/JVM.java
  src/dev/flang/be/jvm/Names.java
  src/dev/flang/be/jvm/runtime/Runtime.java
  tests/native_value/Makefile
  tests/native_value/fz.h
  tests/native_value/native_value.fz
  tests/native_value/native_value.fz.expected_err
  tests/native_value/native_value.fz.expected_out
  tests/native_value/skip_int
Labels: C backend, jvm backend, native

#5023 fe: raise error when adding field without parent in module
  src/dev/flang/ast/AstErrors.java
  src/dev/flang/fe/FrontEndOptions.java
  src/dev/flang/fe/SourceModule.java
  src/dev/flang/tools/Fuzion.java
  src/dev/flang/tools/docs/Docs.java
  src/dev/flang/util/FuzionConstants.java
Labels: bug, front end

#5025 parser/ast: remove `Impl.Kind.Of` and other remnants of `of` keyword
  src/dev/flang/ast/Feature.java
  src/dev/flang/ast/Impl.java
  src/dev/flang/parser/Parser.java
Labels: parser, front end, cleanup

#5027 tests: file/dir, use unicode symbols
  tests/lib_io_dir/lib_io_dir.fz
  tests/lib_io_dir/lib_io_dir.fz.expected_out
  tests/lib_io_file/fileiotests.fz
  tests/lib_io_file/fileiotests.fz.expected_out
Labels: tests

#5030 fuzion runtime: fix possible descriptor leak
  include/posix.c
Labels: backend

#5029 workflow: programmatically determine clang major version
  .github/workflows/linux.yml
Labels: github_actions

#5031 tests add reg. test #1726
  tests/reg_issue1726/Makefile
  tests/reg_issue1726/reg_issue1726.fz
  tests/reg_issue1726/reg_issue1726.fz.expected_err
  tests/reg_issue1726/reg_issue1726.fz.expected_out
Labels: front end, tests

#5034 be/c: zero memory (securely)
  include/fz.h
  include/posix.c
  include/shared.c
  include/win.c
  src/dev/flang/be/c/C.java
Labels: C backend

#5035 tests: add reg. test #2701
  tests/reg_issue2701/Makefile
  tests/reg_issue2701/reg_issue2701.fz
  tests/reg_issue2701/reg_issue2701.fz.expected_err
  tests/reg_issue2701/reg_issue2701.fz.expected_out
Labels: tests

#5037 tests: add test #4422
  tests/reg_issue4422/Makefile
  tests/reg_issue4422/reg_issue4422.fz
  tests/reg_issue4422/reg_issue4422.fz.expected_err
  tests/reg_issue4422/reg_issue4422.fz.expected_out
Labels: bug, front end

#5036 lib: make Lazy inherit from monad
  modules/base/src/Lazy.fz
Labels: base library

#5042 fe: Call, cleanup constructor
  src/dev/flang/ast/Call.java
Labels: cleanup

#5041 rename libfuzion -> libfuzion_rt
  Makefile
  src/dev/flang/be/interpreter/Executor.java
  src/dev/flang/be/jvm/JVM.java
  src/dev/flang/be/jvm/runtime/Runtime.java
Labels: cleanup

#5043 fix devcontainer
  .devcontainer/devcontainer.json
Labels: bug, build infrastructure

#5044 skip native_value test on jvm backend because of #5026
  tests/native_value/skip_jvm
Labels: tests, linux

#5046 fe: remove successive call to v.action
  src/dev/flang/ast/Match.java
Labels: cleanup

#5047 fe: code cleanup `Cond`
  src/dev/flang/ast/Check.java
  src/dev/flang/ast/Cond.java
  src/dev/flang/ast/Context.java
  src/dev/flang/ast/Contract.java
  src/dev/flang/ast/Feature.java
  src/dev/flang/ast/FeatureVisitor.java
  src/dev/flang/fe/SourceModule.java
Labels: cleanup

#5052 mod/terminal: cleanup NYI
  modules/terminal/src/terminal.fz
Labels: base library, cleanup

#5053 lib: cleanup, remove `type_of_lazy`
  modules/base/src/Type.fz
  tests/reg_issue1158_type_of_type_parameters/test_type_of.fz
  tests/reg_issue197/reg_issue197.fz
  tests/reg_issue4557/reg_issue4557.fz
  tests/visibility_scoping/visibility_scoping.fz.expected_err
Labels: base library, cleanup

#5049 fe: remove `If`, create `Match` early
  modules/base/src/net/server.fz
  src/dev/flang/ast/AbstractMatch.java
  src/dev/flang/ast/Call.java
  src/dev/flang/ast/Case.java
  src/dev/flang/ast/Check.java
  src/dev/flang/ast/ContextVisitor.java
  src/dev/flang/ast/Contract.java
  src/dev/flang/ast/Feature.java
  src/dev/flang/ast/FeatureVisitor.java
  src/dev/flang/ast/If.java
  src/dev/flang/ast/IncompatibleResultsOnBranches.java
  src/dev/flang/ast/Loop.java
  src/dev/flang/ast/Match.java
  src/dev/flang/fe/LibraryFeature.java
  src/dev/flang/parser/Parser.java
  tests/incomp_type_in_cases/Makefile
  tests/incomp_type_in_cases/incomp_type_in_cases.fz
  tests/incomp_type_in_cases/incomp_type_in_cases.fz.expected_err
  tests/incomp_type_in_cases/incomp_type_in_cases.fz.expected_out
  tests/loop_negative/looptest_negative.fz.expected_err
  tests/reg_issue2691_b/reg_issue2691_b.fz.expected_err
  tests/reg_issue2775/reg_issue2775.fz.expected_err
  tests/reg_issue662_match_cases_missing/issue662.fz.expected_err
  tests/typeinference_negative/typeinference_negative.fz.expected_err
  tests/unused_result/unused_result.fz.expected_err
  tests/visibility_negative/visibility_negative.fz.expected_err
Labels: front end, cleanup

#5024 fe: fix crash when failing to infer generics of call
  src/dev/flang/ast/Call.java
  tests/reg_issue4988/Makefile
  tests/reg_issue4988/reg_issue4988.fz
  tests/reg_issue4988/reg_issue4988.fz.expected_err
  tests/reg_issue4988/reg_issue4988.fz.expected_out
  tests/reg_issue4988_1/Makefile
  tests/reg_issue4988_1/reg_issue4988_1.fz
  tests/reg_issue4988_1/reg_issue4988_1.fz.expected_err
  tests/reg_issue4988_1/reg_issue4988_1.fz.expected_out
Labels: bug, front end

#5058 lib: Lazy, add comment
  modules/base/src/Lazy.fz
Labels: documentation, base library

#5068 tests: cleanup of NYI comments
  tests/nested_choice/nested_choice.fz
  tests/reg_issue2242/reg_issue2242.fz
  tests/reg_issue960_npe_resolve_syntactic_sugar2/test_issue960.fz
  tests/reg_issue960_npe_resolve_syntactic_sugar2/test_issue960.fz.expected_err
  tests/tuple/tupletest.fz
Labels: tests, cleanup

#5066 tests: include target when generating rerun command
  bin/run_tests.sh
  bin/run_tests_parallel.sh
Labels: tests

#5069 ast: code cleanup
  src/dev/flang/ast/FunctionReturnType.java
Labels: front end, cleanup

#5071 fuzion runtime: remove commented code
  include/shared.c
Labels: C backend, cleanup

#5072 be/c: move file/time specific stuff to win.c/posix.c
  include/posix.c
  include/shared.c
  include/win.c
Labels: C backend, cleanup

#5074 be/c: convert some functions to windows native
  include/win.c
Labels: windows

#5079 Makefile: include API docs in make target `doc`
  Makefile
Labels: enhancement, build infrastructure

#5076 lib, doc: Workaround to improve DFA performance: Move local instances to `unit`
  bin/ebnf.fz
  modules/base/src/container/abstract_array.fz
  modules/base/src/io/file/write.fz
  modules/base/src/list.fz
Labels: documentation, base library, performance issue

#5081 win: fix fzE_dir_read, exclude NULL-byte from length
  include/win.c
Labels: windows

#5017 ast: specify possible argument count for suggested features in error message
  src/dev/flang/ast/AstErrors.java
  tests/partial_application_negative/partial_application_negative.fz.expected_err
  tests/reg_issue2386/reg_issue2386.fz.expected_err
  tests/reg_issue4251/reg_issue4251.fz.expected_err
  tests/reg_issue4457/reg_issue4457.fz.expected_err
Labels: enhancement, front end

#5087 win: build args and env in win.c
  include/fz.h
  include/posix.c
  include/win.c
  modules/base/src/native.fz
  modules/base/src/os/processes.fz
Labels: backend, windows

#5088 tests: try workaround broken pipe problem
  bin/run_tests_parallel.sh
Labels: build infrastructure

#5089 win: fzE_date_time add support for nano seconds
  include/win.c
Labels: windows

#5090 fz.h: update outdated comment
  include/fz.h
Labels: cleanup

#5091 win: fix test process
  include/win.c
  tests/process/test_process.fz
  tests/process/test_process.fz.expected_out
Labels: windows

#5092 makefile: target build/include depends on all files in include
  Makefile
Labels: build infrastructure, cleanup

#5097 fuzion_rt: change fzE_last_error to i64
  include/fz.h
  include/posix.c
  include/win.c
  modules/base/src/native.fz
Labels: backend

#5094 ast: fix `DFA reading uninitialized field`
  src/dev/flang/ast/Block.java
  tests/lib_concur_sync/lib_concur_sync.fz
Labels: bug, front end

#5086 tests: cleanup in visibility scoping
  tests/uninitialized_field_negative/Makefile
  tests/uninitialized_field_negative/uninitialized_field_negative.fz
  tests/uninitialized_field_negative/uninitialized_field_negative.fz.expected_err
  tests/uninitialized_field_negative/uninitialized_field_negative.fz.expected_out
  tests/visibility_scoping/visibility_scoping.fz
Labels: tests, cleanup

#5101 windows: readd workaround for unicode problem
  tests/check_simple_example_c.sh
  tests/check_simple_example_effect.sh
  tests/check_simple_example_int.sh
  tests/check_simple_example_jvm.sh
Labels: windows

#5099 fuzion_rt: cleanups, comments
  include/fz.h
  include/posix.c
  include/win.c
  modules/base/src/native.fz
  src/dev/flang/be/c/C.java
  src/dev/flang/be/c/Intrinsics.java
Labels: cleanup

#5108 lib: add process.close_in
  modules/base/src/os/process.fz
Labels: enhancement, base library

#5112 lib: implement calendar.duration `lteq`
  modules/base/src/time/calendar_duration.fz
Labels: enhancement, base library

#5110 port run_tests to fuzion
  bin/run_tests.fz
Labels: enhancement, build infrastructure

#5118 lib: add `order`, choice of less/greater/equal
  modules/base/src/container/ps_map.fz
  modules/base/src/container/sorted_array.fz
  modules/base/src/equals.fz
  modules/base/src/numeric.fz
  modules/base/src/order.fz
  tests/lib_container_sorted_array/lib_container_sorted_array.fz
Labels: enhancement, base library

#5125 fuzion_rt: refine comments
  include/fz.h
Labels: documentation, cleanup

#5128 fix merge incongruence
  modules/base/src/time/calendar_duration.fz
Labels: bug, base library

#5123 lib: String add write_to, writing String to installed writer
  modules/base/src/String.fz
Labels: enhancement, base library

#5126 run_tests.fz cleanups
  bin/run_tests.fz
Labels: build infrastructure, cleanup

#5131 fe: suppress subsequent error on argument count in #5114
  src/dev/flang/ast/AbstractFeature.java
  src/dev/flang/ast/AstErrors.java
  src/dev/flang/ast/Function.java
  src/dev/flang/fe/SourceModule.java
Labels: enhancement

#5138 remove (un)setenv
  bin/aspell.dict
  include/fz.h
  include/posix.c
  include/win.c
  modules/base/src/envir/vars.fz
  modules/base/src/fuzion/sys/env_vars.fz
  src/dev/flang/be/c/Intrinsics.java
  src/dev/flang/be/interpreter/Intrinsics.java
  src/dev/flang/be/jvm/Intrinsix.java
  src/dev/flang/fuir/analysis/dfa/DFA.java
  src/dev/flang/fuir/cfg/CFG.java
  tests/envir_vars/envir_vars.fz
  tests/envir_vars/envir_vars.fz.expected_out
Labels: base library, backend, cleanup

#5136 lib: change ordered_map arg types to Sequence
  modules/base/src/container/ordered_map.fz
Labels: base library, cleanup

#5135 fe: Avoid creation of lambda feature in case of error
  src/dev/flang/ast/Function.java
  src/dev/flang/ast/Loop.java
  src/dev/flang/fe/SourceModule.java
  tests/reg_issue4694/reg_issue4694.fz.expected_err
Labels: front end, cleanup

#5143 run windows tests every workday
  .github/workflows/windows.yml
Labels: tests, windows

#5144 makefile: add helper to rerecord effects
  Makefile
Labels: enhancement, build infrastructure

#5132 fe: Select, fix NPE
  src/dev/flang/ast/Select.java
Labels: bug, front end

#5146 lib: do not use fully qualified name where not necessary
  modules/base/src/fuzion/java.fz
  modules/base/src/fuzion/std.fz
Labels: base library, cleanup

#5148 build: suppress makefile output for cleaner output of negative tests
  tests/negative.mk
Labels: build infrastructure, tests

#5150 fz: change all options to camelCase
  Makefile
  src/dev/flang/tools/Fuzion.java
  tests/compile.mk
  tests/fe.mk
  tests/fz_cmd/fz_cmd.fz.expected_err
  tests/inherit_postcondition/Makefile
  tests/modules/Makefile
  tests/reg_issue1109/Makefile
  tests/reg_issue2237/Makefile
  tests/reg_issue3772/Makefile
  tests/visibility_modules/Makefile
  tests/visibility_modules_negative/Makefile
Labels: fz tool, cleanup

#5139 lib: fix hierarchy of faults
  modules/base/src/fuzion/runtime/check_fault.fz
  modules/base/src/fuzion/runtime/contract_fault.fz
  modules/base/src/fuzion/runtime/post_fault.fz
  modules/base/src/fuzion/runtime/pre_fault.fz
  tests/assignments/assignments.fz.effect
  tests/atomic/test_atomic.fz.effect
  tests/catch_postcondition/catch_postcondition.fz.expected_err_int
  tests/catch_postcondition/catch_postcondition.fz.expected_err_jvm
  tests/compile_time_type_casts_negative2/compile_time_type_casts_negative2.fz.expected_err_int
  tests/compile_time_type_casts_negative2/compile_time_type_casts_negative2.fz.expected_err_jvm
  tests/contracts_negative/SquareRoot.fz.expected_err_int
  tests/contracts_negative/SquareRoot.fz.expected_err_jvm
  tests/hello/HelloWorld.fz.effect
  tests/i18n_default_test/i18n_default_test.fz.effect
  tests/lib_concur_sync/lib_concur_sync.fz.effect
  tests/lib_fileio_mmap/mmap_test.fz.effect
  tests/lib_io_dir/lib_io_dir.fz.effect
  tests/lib_io_file/fileiotests.fz.effect
  tests/lib_memoize/lib_memoize.fz.effect
  tests/mod_lock_free_Map/ctrie_test.fz.effect
  tests/mod_lock_free_Map_threads/ctrie_threads.fz.effect
  tests/reg_issue2194/reg_issue2194.fz.expected_err_int
  tests/reg_issue2194/reg_issue2194.fz.expected_err_jvm
  tests/reg_issue2325/reg_issue2325.fz.expected_err_int
  tests/reg_issue2325/reg_issue2325.fz.expected_err_jvm
  tests/reg_issue270/issue270.fz.expected_err_int
  tests/reg_issue270/issue270.fz.expected_err_jvm
  tests/reg_issue2745/reg_issue2745.fz.expected_err_int
  tests/reg_issue2745/reg_issue2745.fz.expected_err_jvm
  tests/reg_issue3178/reg_issue3178.fz.expected_err_c
  tests/reg_issue3178/reg_issue3178.fz.expected_err_jvm
  tests/reg_issue3178/reg_issue3178.fz.expected_out_c
  tests/reg_issue3178/skip_c
  tests/reg_issue4353/reg_issue4353.fz.expected_err_int
  tests/reg_issue4353/reg_issue4353.fz.expected_err_jvm
  tests/reg_issue4609/reg_issue4609.fz.expected_err_int
  tests/reg_issue4609/reg_issue4609.fz.expected_err_jvm
  tests/sequence_sliding/sequence_sliding.fz.expected_err_int
  tests/sequence_sliding/sequence_sliding.fz.expected_err_jvm
Labels: bug, base library

#5113 lib: mark Set.add abstract
  modules/base/src/container/Set.fz
  modules/base/src/container/ps_set.fz
  modules/base/src/list.fz
  modules/lock_free/src/lock_free/set_of_hashable.fz
  tests/sequence/Makefile
  tests/sequence/sequence.fz
  tests/sequence/sequence.fz.expected_err
  tests/sequence/sequence.fz.expected_out
Labels: base library, cleanup

#5152 Revert "workflow: change linux workflow"
  .github/workflows/linux.yml
Labels: build infrastructure

#5154 lib: add String.lines, splitting the String at \n
  modules/base/src/String.fz
  src/dev/flang/tools/fzjava/FeatureWriter.java
Labels: enhancement, base library

#5158 lib: change visibility of trim_start/trim_end
  modules/base/src/String.fz
Labels: base library

#5160 fe: Select, add comment
  src/dev/flang/ast/Select.java
Labels: documentation, front end

#5161 AbstractType, make cache fields private
  src/dev/flang/ast/AbstractType.java
Labels: front end, cleanup

#5162 ast: remove seemingly abandoned method
  src/dev/flang/ast/AbstractType.java
Labels: front end, cleanup

#5134 test: use run_tests.fz
  Makefile
  bin/run_tests.fz
  bin/run_tests.sh
  bin/run_tests_parallel.sh
Labels: enhancement, build infrastructure

#5165 lib: change comment of NYI for processes
  modules/base/src/os.fz
  modules/base/src/os/process.fz
Labels: base library, cleanup

#5169 run_tests: port test enum to fuzion
  bin/run_tests.fz
Labels: build infrastructure, cleanup

#5168 run_tests: fix failing precondition in failed tests enumeration
  bin/run_tests.fz
Labels: bug, build infrastructure

#5133 Added predicate functions for order
  modules/base/src/order.fz
Labels: enhancement, base library

#5170 run_tests: run append_line synchronized
  bin/run_tests.fz
  modules/base/src/concur/sync.fz
  modules/base/src/concur/thread_pool.fz
  tests/lib_concur_sync/lib_concur_sync.fz
Labels: enhancement, base library, cleanup

#4987 fe: Call.resolveTypes, refactoring
  src/dev/flang/ast/Call.java
  tests/choice_negative/choice_negative.fz.expected_err
Labels: front end, cleanup

#5171 ast: use This.thiz instead of constructor
  src/dev/flang/ast/AbstractCurrent.java
  src/dev/flang/ast/Contract.java
  src/dev/flang/ast/FeatureAndOuter.java
  src/dev/flang/ast/This.java
Labels: cleanup
