Repository tokiwa-software/fuzion, pull requests merged in 2025-06, with the labels that each got.

#5304 fuir: fix `Clazz.findOuter`
  src/dev/flang/ast/AbstractType.java
  src/dev/flang/fuir/Clazz.java
  tests/reg_issue5302/Makefile
  tests/reg_issue5302/reg_issue5302.fz
  tests/reg_issue5302/reg_issue5302.fz.expected_err
  tests/reg_issue5302/reg_issue5302.fz.expected_out
Labels: bug, dfa/monomorphization

#5326 ast: Change choice into Choice at start of error msg for consistency
  src/dev/flang/ast/AstErrors.java
  tests/choice_negative/choice_negative.fz.expected_err
Labels: front end, cleanup

#5327 lib: Sequence, remove confusing operators
  modules/base/src/Sequence.fz
  tests/choice_mix/choice_mix.fz
  tests/qualified_declaration/qualified_declaration.fz
  tests/rosettacode_factors_of_an_integer/factors.fz
  tests/rosettacode_factors_of_an_integer/factors.fz.expected_out
  tests/rosettacode_man_or_boy/man_or_boy.fz
  tests/rosettacode_primes/primes.fz
  tests/rosettacode_primes/primes.fz.expected_out
Labels: base library, cleanup

#5331 lib: move ignore to own file
  modules/base/src/id.fz
  modules/base/src/ignore.fz
Labels: base library, cleanup

#5334 effect.fz: fix comment
  modules/base/src/effect.fz
Labels: base library, cleanup

#5340 lib: improve error messages
  modules/base/src/fuzion/sys/fileio.fz
Labels: enhancement, base library

#5338 fe: isAssignable return YesNo instead of bool
  src/dev/flang/ast/AbstractAssign.java
  src/dev/flang/ast/AbstractMatch.java
  src/dev/flang/ast/AbstractType.java
  src/dev/flang/ast/AstErrors.java
  src/dev/flang/ast/Block.java
  src/dev/flang/ast/Call.java
  src/dev/flang/ast/Expr.java
  src/dev/flang/ast/Feature.java
  src/dev/flang/ast/Function.java
  src/dev/flang/ast/InlineArray.java
  src/dev/flang/ast/Tag.java
  src/dev/flang/fe/SourceModule.java
  src/dev/flang/fuir/GeneratingFUIR.java
  src/dev/flang/lsp/feature/Commands.java
  src/dev/flang/util/YesNo.java
  tests/reg_issue3648/reg_issue3648.fz.expected_err
Labels: enhancement, front end

#5173 parser: simplify parsing destructuring with feature declarations
  bin/run_tests.fz
  modules/base/src/String.fz
  modules/base/src/container/Map.fz
  modules/base/src/container/Mutable_Hash_Map.fz
  modules/base/src/container/expanding_array.fz
  modules/base/src/container/hash_map.fz
  modules/base/src/container/mutable_tree_map.fz
  modules/base/src/container/ps_map.fz
  modules/base/src/fuzion/runtime/fault.fz
  modules/base/src/integer.fz
  modules/base/src/num/ryu.fz
  modules/base/src/os/processes.fz
  modules/base/src/time/duration.fz
  modules/base/src/u16.fz
  modules/base/src/u32.fz
  modules/base/src/u64.fz
  modules/base/src/u8.fz
  modules/base/src/uint.fz
  modules/lock_free/src/lock_free/Map.fz
  modules/nom/src/nom/multi.fz
  modules/nom/src/nom/parsers/json.fz
  src/dev/flang/ast/AbstractAssign.java
  src/dev/flang/ast/Assign.java
  src/dev/flang/ast/AstErrors.java
  src/dev/flang/ast/Destructure.java
  src/dev/flang/ast/Feature.java
  src/dev/flang/ast/FeatureVisitor.java
  src/dev/flang/ast/Select.java
  src/dev/flang/lsp/shared/ParserTool.java
  src/dev/flang/parser/Parser.java
  tests/base16/base16_test.fz
  tests/base32/base32_test.fz
  tests/base32hex/base32hex_test.fz
  tests/base64/base64_test.fz
  tests/base64url/base64url_test.fz
  tests/nom/nom_test.fz
  tests/reg_issue108/reg_issue108.fz
  tests/reg_issue122/reg_issue122.fz
  tests/reg_issue1294/issue1294.fz
  tests/reg_issue228/reg_issue228.fz
  tests/reg_issue238_array_index_out_of_bounds/issue238.fz
  tests/reg_issue3362/reg_issue3362.fz
  tests/reg_issue4518/reg_issue4518.fz
  tests/reg_issue4518/reg_issue4518.fz.expected_err
  tests/reg_issue465/reg_issue465.fz
  tests/ryu/ryu_test.fz
  tests/tuple/tupletest.fz
  tests/tuple/tupletest.fz.expected_out
  tests/tuple_negative/tuple_negative.fz
  tests/tuple_negative/tuple_negative.fz.expected_err
  tests/visibility/visibility.fz
Labels: Fuzion language, parser, cleanup

#5349 lib: list.as_string, syntax simplification
  modules/base/src/list.fz
Labels: base library, cleanup

#5356 lib: add feature realtime
  modules/base/src/realtime.fz
Labels: enhancement, base library

#5357 lib: net, improve error mesages
  modules/base/src/fuzion/sys/net.fz
Labels: enhancement, base library

#5350 modules: add json_encode
  Makefile
  modules/json_encode/src/json_encode.fz
  tests/mod_json_encode/Makefile
  tests/mod_json_encode/mod_json_encode.fz
  tests/mod_json_encode/mod_json_encode.fz.expected_err
  tests/mod_json_encode/mod_json_encode.fz.expected_out
Labels: enhancement, base library

#5360 lib: cleanup NYI on `Array`, add type parameter
  include/fz.h
  include/posix.c
  include/win.c
  modules/base/src/ffi.fz
  modules/base/src/fuzion/jvm.fz
  modules/base/src/fuzion/sys.fz
  modules/base/src/fuzion/sys/env_vars.fz
  modules/base/src/fuzion/sys/internal_array.fz
  modules/base/src/internal.fz
  modules/base/src/io/file/stat.fz
  modules/base/src/native.fz
  modules/base/src/os/processes.fz
  src/dev/flang/ast/Feature.java
  src/dev/flang/be/jvm/Types.java
  src/dev/flang/fuir/FUIR.java
Labels: base library, cleanup

#5351 lib: process.send_signal
  include/fz.h
  include/posix.c
  include/win.c
  modules/base/src/native.fz
  modules/base/src/os/process.fz
  modules/base/src/os/processes.fz
  modules/base/src/os/signal.fz
  modules/base/src/os/signals.fz
Labels: enhancement, base library

#5371 fix windows build
  include/win.c
Labels: bug, windows

#5372 ast: cleanups, improve naming
  src/dev/flang/ast/AbstractCall.java
  src/dev/flang/ast/AbstractType.java
  src/dev/flang/ast/Call.java
  src/dev/flang/ast/Expr.java
  src/dev/flang/ast/Impl.java
  src/dev/flang/ast/ResolvedNormalType.java
  src/dev/flang/ast/UnresolvedType.java
Labels: front end, cleanup

#5373 ast: Tag, move checkchoice to checktypes phase
  src/dev/flang/ast/Feature.java
  src/dev/flang/ast/Tag.java
Labels: front end, cleanup

#5376 ast: abstract assign, checkTypes, check for direct assignability
  src/dev/flang/ast/AbstractAssign.java
Labels: enhancement, front end

#5389 docs: for function features hide inner (inherited) functions and fields
  src/dev/flang/tools/docs/Html.java
Labels: bug, documentation

#5390 docs: api: improve alignment in feature list
  assets/docs/style.css
  src/dev/flang/tools/docs/Html.java
Labels: documentation, enhancement

#5380 examples/gtk: add test for pkg-config and gtk, documentation
  examples/gtk/Makefile
  examples/gtk/gtk.fz
Labels: documentation, enhancement

#5393 docs: require leading blank line for code blocks in comments
  src/dev/flang/tools/docs/Html.java
Labels: bug, documentation

#5392 docs: fix missing comments in API docs
  src/dev/flang/tools/docs/Util.java
Labels: bug, documentation

#5396 loop: add position for `else`
  src/dev/flang/ast/Loop.java
  src/dev/flang/parser/Parser.java
Labels: front end, cleanup

#5399 ast: remove unused field
  src/dev/flang/ast/ResolvedNormalType.java
Labels: base library, front end, cleanup

#5400 ast: InlineArray, fix target type
  src/dev/flang/ast/InlineArray.java
Labels: bug, front end

#5403 docs: fix links of base module feature displayed in other modules
  src/dev/flang/tools/docs/Html.java
Labels: bug, documentation

#5406 doc: fix asciidoc code for Match entry in fum file
  src/dev/flang/fe/LibraryModule.java
Labels: bug, documentation

#5408 make: set failure level for `asciidoctor` to `WARN`
  Makefile
Labels: enhancement, build infrastructure

#5410 fe: cleanup AbstractType.visit
  src/dev/flang/ast/AbstractType.java
  src/dev/flang/ast/ResolvedNormalType.java
  src/dev/flang/ast/ResolvedParametricType.java
  src/dev/flang/ast/UnresolvedType.java
  src/dev/flang/fe/GenericType.java
  src/dev/flang/fe/LibraryType.java
  src/dev/flang/fe/NormalType.java
Labels: cleanup

#5411 ast: update comments, remove Types.intern note
  src/dev/flang/ast/ResolvedNormalType.java
Labels: cleanup

#5407 ast: remove `ast/Generic`
  src/dev/flang/ast/AbstractFeature.java
  src/dev/flang/ast/AbstractType.java
  src/dev/flang/ast/AstErrors.java
  src/dev/flang/ast/Call.java
  src/dev/flang/ast/Context.java
  src/dev/flang/ast/Feature.java
  src/dev/flang/ast/FormalGenerics.java
  src/dev/flang/ast/Generic.java
  src/dev/flang/ast/NumLiteral.java
  src/dev/flang/ast/ResolvedParametricType.java
  src/dev/flang/ast/ResolvedType.java
  src/dev/flang/ast/UnresolvedType.java
  src/dev/flang/fe/FeErrors.java
  src/dev/flang/fe/GenericType.java
  src/dev/flang/fe/LibraryModule.java
  src/dev/flang/fe/LibraryOut.java
  src/dev/flang/fe/NormalType.java
  src/dev/flang/fuir/Clazz.java
  src/dev/flang/lsp/feature/Rename.java
  src/dev/flang/lsp/shared/TypeTool.java
Labels: front end, cleanup

#5420 ast: explicitly specify if innerFixed in some places
  src/dev/flang/ast/AbstractFeature.java
  src/dev/flang/ast/Call.java
  src/dev/flang/ast/OuterType.java
Labels: enhancement, front end

#5422 fe: remove `t_ADDRESS`
  src/dev/flang/ast/AbstractType.java
  src/dev/flang/ast/ArtificialBuiltInType.java
  src/dev/flang/ast/Feature.java
  src/dev/flang/ast/ResolvedNormalType.java
  src/dev/flang/ast/Types.java
  src/dev/flang/ast/UnresolvedType.java
  src/dev/flang/fe/LibraryModule.java
  src/dev/flang/fe/LibraryOut.java
  src/dev/flang/fuir/Clazz.java
  src/dev/flang/lsp/shared/FeatureTool.java
  src/dev/flang/tools/docs/Docs.java
Labels: cleanup

#5423 ast: remove special handling in This.java
  src/dev/flang/ast/This.java
Labels: front end, cleanup

#5428 fe: remove unused formal parameters
  src/dev/flang/ast/NumLiteral.java
  src/dev/flang/ast/ParsedOperatorCall.java
  src/dev/flang/fe/SourceModule.java
  src/dev/flang/parser/OpExpr.java
Labels: cleanup

#5442 ast: remove boxed variant of type parameter types
  src/dev/flang/ast/AbstractType.java
  src/dev/flang/ast/AstErrors.java
  src/dev/flang/ast/ResolvedParametricType.java
  src/dev/flang/fe/GenericType.java
Labels: cleanup

#5444 ast: Type, merge isGenericArgument and typeKind
  src/dev/flang/ast/AbstractFeature.java
  src/dev/flang/ast/AbstractType.java
  src/dev/flang/ast/BuiltInType.java
  src/dev/flang/ast/ParsedType.java
  src/dev/flang/ast/QualThisType.java
  src/dev/flang/ast/ResolvedNormalType.java
  src/dev/flang/ast/ResolvedParametricType.java
  src/dev/flang/ast/ResolvedType.java
  src/dev/flang/ast/TypeKind.java
  src/dev/flang/ast/UnresolvedType.java
  src/dev/flang/fe/GenericType.java
  src/dev/flang/fe/LibraryFeature.java
  src/dev/flang/fe/LibraryModule.java
  src/dev/flang/fe/LibraryOut.java
  src/dev/flang/fe/NormalType.java
  src/dev/flang/fuir/Clazz.java
Labels: front end, cleanup
