Repository tokiwa-software/fuzion, pull requests merged in 2025-02, with the labels that each got.

#4709 tests: add reg test #659
  tests/reg_issue659/Makefile
  tests/reg_issue659/reg_issue659.fz
  tests/reg_issue659/reg_issue659.fz.expected_err
  tests/reg_issue659/reg_issue659.fz.expected_out
Labels: bug, front end

#4719 cleanup: Call.toString
  src/dev/flang/ast/AbstractCall.java
  src/dev/flang/ast/Call.java
  src/dev/flang/fe/LibraryCall.java
Labels: front end, cleanup

#4721 base: add a `property.countable` feature and use it in`Sequence`
  modules/base/src/Sequence.fz
  modules/base/src/count.fz
  modules/base/src/property/countable.fz
  tests/free_types_negative/test_free_types_negative.fz.expected_err
  tests/property_countable_count/Makefile
  tests/property_countable_count/ex_count.fz
  tests/property_countable_count/ex_count.fz.expected_err
  tests/property_countable_count/ex_count.fz.expected_out
Labels: enhancement, base library

#4704 fe/parser: fix short handle select parsing
  src/dev/flang/ast/AstErrors.java
  src/dev/flang/ast/Select.java
  src/dev/flang/be/interpreter/Interpreter.java
  src/dev/flang/parser/Parser.java
  tests/reg_issue2913/Makefile
  tests/reg_issue2913/reg_issue2913.fz
  tests/reg_issue2913/reg_issue2913.fz.expected_err
  tests/reg_issue2913/reg_issue2913.fz.expected_out
  tests/reg_issue4408/Makefile
  tests/reg_issue4408/reg_issue4408.fz
  tests/reg_issue4408/reg_issue4408.fz.expected_err
  tests/reg_issue4408/reg_issue4408.fz.expected_out
  tests/select_clause/Makefile
  tests/select_clause/select_clause.fz
  tests/select_clause/select_clause.fz.expected_err
  tests/select_clause/select_clause.fz.expected_out
  tests/select_clause_negative/Makefile
  tests/select_clause_negative/select_clause_negative.fz
  tests/select_clause_negative/select_clause_negative.fz.expected_err
  tests/select_clause_negative/select_clause_negative.fz.expected_out
Labels: bug, front end

#4723 native: add `fzE_errno`
  Makefile
  include/fz.h
  include/posix.c
  include/win.c
  modules/base/src/native.fz
  modules/base/src/os/processes.fz
  src/dev/flang/be/c/Intrinsics.java
  tests/process/test_process.fz
  tests/process/test_process.fz.expected_out
Labels: enhancement, native

#4727 ast: fix setting context for _extension_ features
  src/dev/flang/ast/Context.java
  src/dev/flang/ast/Feature.java
  tests/reg_issue3549/Makefile
  tests/reg_issue3549/reg_issue3549.fz
  tests/reg_issue3549/reg_issue3549.fz.expected_err
  tests/reg_issue3549/reg_issue3549.fz.expected_out
Labels: bug, front end

#4728 cleanups, related to `fzE_last_error`
  include/fz.h
  include/posix.c
  include/win.c
  modules/base/src/native.fz
  modules/base/src/os/processes.fz
Labels: cleanup

#4732 fe: fix inheritance for contracts
  modules/base/src/container/abstract_array.fz
  modules/base/src/i128.fz
  modules/base/src/i16.fz
  modules/base/src/i32.fz
  modules/base/src/i64.fz
  modules/base/src/i8.fz
  modules/base/src/num/complex.fz
  modules/base/src/num/fraction.fz
  modules/base/src/num/wrap_around.fz
  modules/base/src/numeric.fz
  modules/base/src/property/equatable.fz
  modules/base/src/u128.fz
  modules/base/src/u16.fz
  modules/base/src/u32.fz
  modules/base/src/u64.fz
  modules/base/src/u8.fz
  src/dev/flang/ast/Contract.java
  src/dev/flang/ast/FeatureName.java
  src/dev/flang/fe/FrontEnd.java
  tests/catch_preconditions/catch_precondition.fz
  tests/catch_preconditions/catch_precondition.fz.expected_out
  tests/i128/i128_test.fz.expected_out
  tests/reg_issue3178/reg_issue3178.fz.expected_err_jvm
  tests/reg_issue3191/reg_issue3191.fz
  tests/reg_issue3191/reg_issue3191.fz.expected_err
  tests/reg_issue3191/reg_issue3191.fz.expected_out
  tests/reg_issue3191/skip
Labels: bug, front end

#4696 lib: Add heuristics to avoid `Sequence.concat` to cause quadratic performance
  modules/base/src/Sequence.fz
  modules/base/src/container/expanding_array.fz
  tests/atomic/test_atomic.fz.effect
  tests/hello/HelloWorld.fz.effect
  tests/i18n_default_test/i18n_default_test.fz.effect
  tests/lib_concur_sync/lib_concur_sync.fz.effect
  tests/mod_lock_free_Map_threads/ctrie_threads.fz.effect
Labels: enhancement, base library, performance issue

#4736 ast: change control flow in getActualResultType
  src/dev/flang/ast/Call.java
Labels: front end, cleanup

#4734 lib: changes related to property.equatable
  bin/ebnf.fz
  modules/base/src/Sequence.fz
  modules/base/src/array.fz
  modules/base/src/concur/thread_pool.fz
  modules/base/src/container/Linked_List.fz
  modules/base/src/container/Set.fz
  modules/base/src/int.fz
  modules/base/src/interval.fz
  modules/base/src/io/buffered/reader.fz
  modules/base/src/list.fz
  modules/base/src/option.fz
  modules/base/src/outcome.fz
  modules/base/src/property/equatable.fz
  modules/base/src/switch.fz
  tests/free_types_negative/test_free_types_negative.fz.expected_err
  tests/lib_property_equatable/lib_property_equatable.fz
  tests/reg_issue3801/reg_issue3801.fz
  tests/transducers/transducertest.fz
Labels: base library, cleanup

#4741 fe: rename `createThisType` -> `createSelfType`
  src/dev/flang/ast/AbstractFeature.java
  src/dev/flang/ast/Types.java
  src/dev/flang/fe/LibraryFeature.java
Labels: front end, cleanup

#4743 fe: fix choice-this-types
  modules/base/src/option.fz
  modules/base/src/outcome.fz
  modules/base/src/switch.fz
  src/dev/flang/ast/AbstractMatch.java
  src/dev/flang/ast/AbstractType.java
  src/dev/flang/ast/Expr.java
  src/dev/flang/ast/Feature.java
  src/dev/flang/ast/ResolvedNormalType.java
Labels: bug, front end

#4755 lib: float, cleanup comparison
  modules/base/src/f32.fz
  modules/base/src/f64.fz
  modules/base/src/float.fz
  src/dev/flang/be/c/C.java
  src/dev/flang/be/c/Intrinsics.java
  src/dev/flang/be/interpreter/Intrinsics.java
  src/dev/flang/be/jvm/runtime/Intrinsics.java
  src/dev/flang/fuir/analysis/dfa/DFA.java
  src/dev/flang/fuir/cfg/CFG.java
Labels: base library, cleanup

#4726 fuir: add serialization
  .github/workflows/apple.yml
  .github/workflows/linux.yml
  .github/workflows/windows.yml
  src/dev/flang/be/c/C.java
  src/dev/flang/be/jvm/JVM.java
  src/dev/flang/fe/FrontEndOptions.java
  src/dev/flang/fuir/Clazz.java
  src/dev/flang/fuir/ClazzRecord.java
  src/dev/flang/fuir/DfaFUIR.java
  src/dev/flang/fuir/GeneratingFUIR.java
  src/dev/flang/fuir/LibraryFuir.java
  src/dev/flang/fuir/SiteRecord.java
  src/dev/flang/fuir/analysis/dfa/DFA.java
  src/dev/flang/tools/Fuzion.java
  src/dev/flang/tools/docs/Docs.java
  src/dev/flang/tools/fzjava/FZJava.java
Labels: enhancement, dfa/monomorphization

#4759 ast: add comment on formal generics
  src/dev/flang/ast/FormalGenerics.java
Labels: documentation, front end

#4761 enable fuir serialization for jenkins builds
  Dockerfile
Labels: build infrastructure

#4758 ast: small cleanup in `AbstractCall`
  src/dev/flang/ast/AbstractCall.java
  src/dev/flang/ast/AbstractMatch.java
  src/dev/flang/fe/LibraryCall.java
Labels: front end, cleanup

#4760 base: remove `sum`, add `Sequence.sum` and `Sequence.product`
  modules/base/src/Sequence.fz
  modules/base/src/count.fz
  modules/base/src/sum.fz
  tests/property_countable_count/ex_count.fz
  tests/reg_issue1294/issue1294.fz
  tests/reg_issue3371/reg_issue3371.fz
  tests/reg_issue3658/reg_issue3658.fz
  tests/reg_issue3659/reg_issue3659.fz
  tests/reg_issue4480/reg_issue4480.fz
  tests/reg_issue4480/reg_issue4480.fz.expected_err
Labels: base library, cleanup

#4765 jvm: better error handling for unreachable code
  src/dev/flang/be/jvm/Choices.java
  src/dev/flang/be/jvm/JVM.java
Labels: enhancement, jvm backend

#4768 base/Sequence: simplify `average` and `variance` features
  modules/base/src/Sequence.fz
Labels: base library, cleanup

#4764 ast: fix crash when using type constraints
  src/dev/flang/ast/AbstractFeature.java
  src/dev/flang/ast/Context.java
  src/dev/flang/ast/Contract.java
  src/dev/flang/ast/Feature.java
  tests/reg_issue4353/Makefile
  tests/reg_issue4353/reg_issue4353.fz
  tests/reg_issue4353/reg_issue4353.fz.expected_err_c
  tests/reg_issue4353/reg_issue4353.fz.expected_err_int
  tests/reg_issue4353/reg_issue4353.fz.expected_err_jvm
  tests/reg_issue4353/reg_issue4353.fz.expected_out_c
  tests/reg_issue4353/reg_issue4353.fz.expected_out_int
  tests/reg_issue4353/reg_issue4353.fz.expected_out_jvm
Labels: bug, front end

#4772 cleanup: remove `HasGlobalIndex` and other small cleanups
  bin/aspell.dict
  src/dev/flang/ast/AbstractCase.java
  src/dev/flang/ast/BoolConst.java
  src/dev/flang/ast/Call.java
  src/dev/flang/ast/Check.java
  src/dev/flang/ast/Context.java
  src/dev/flang/ast/Expr.java
  src/dev/flang/ast/HasGlobalIndex.java
  src/dev/flang/ast/Impl.java
  src/dev/flang/ast/Nop.java
  src/dev/flang/ast/QualThisType.java
  src/dev/flang/ast/Select.java
  src/dev/flang/be/interpreter/Layout.java
  src/dev/flang/fe/FrontEnd.java
  src/dev/flang/fuir/analysis/AbstractInterpreter.java
  src/dev/flang/opt/Optimizer.java
Labels: cleanup

#4774 update java patch
  src/dev/flang/fuir/analysis/AbstractInterpreter2.java.patch
Labels: build infrastructure

#4775 Jvm fix verifier error in mandelbrot test
  src/dev/flang/be/jvm/Choices.java
  tests/mandelbrot/Makefile
  tests/mandelbrot/mandelbrot.fz
  tests/mandelbrot/mandelbrot.fz.expected_err
  tests/mandelbrot/mandelbrot.fz.expected_out
Labels: bug, jvm backend

#4777 ast: move `replace_type_parameters_of_cotype_origin` to `getActualResultType`
  src/dev/flang/ast/Call.java
Labels: cleanup

#4778 ast: call.resolveTypes move resolveImmediateFunctionCall to end
  src/dev/flang/ast/Call.java
Labels: cleanup

#4780 be/int: cleanup NYI in `getField`
  src/dev/flang/be/interpreter/Interpreter.java
Labels: cleanup

#4782 be/jvm: remove outdated NYI
  src/dev/flang/be/jvm/CodeGen.java
Labels: cleanup, jvm backend

#4783 lib: small cleanup of NYI and unnecessary parens
  modules/base/src/fuzion/runtime/check_fault.fz
  modules/base/src/fuzion/runtime/post_fault.fz
  modules/base/src/fuzion/runtime/pre_fault.fz
Labels: base library, cleanup

#4784 tests: remove some outdated NYI
  tests/compile_time_type_casts_negative2/compile_time_type_casts_negative2.fz
  tests/compile_time_type_casts_negative2/compile_time_type_casts_negative2.fz.expected_err_int
  tests/compile_time_type_casts_negative2/compile_time_type_casts_negative2.fz.expected_out_c
  tests/compile_time_type_casts_negative2/compile_time_type_casts_negative2.fz.expected_out_int
  tests/compile_time_type_casts_negative2/compile_time_type_casts_negative2.fz.expected_out_jvm
  tests/local_mutate_negative/test_local_mutate_neg.fz
  tests/local_mutate_negative/test_local_mutate_neg.fz.expected_err
  tests/mod_lock_free_Map_threads/skip_int
  tests/reg_issue3308/reg_issue3308.fz
  tests/reg_issue3308/reg_issue3308.fz.expected_out
Labels: tests, cleanup

#4786 parser: prefix operator precedence over postfix
  modules/base/src/numeric.fz
  src/dev/flang/parser/OpExpr.java
  tests/reg_issue3081/Makefile
  tests/reg_issue3081/reg_issue3081.fz
  tests/reg_issue3081/reg_issue3081.fz.expected_err
  tests/reg_issue3081/reg_issue3081.fz.expected_out
Labels: enhancement, Fuzion language, parser

#4791 ast: ResolvedNormalType.asThis do not create this type of universe
  src/dev/flang/ast/ResolvedNormalType.java
Labels: bug, front end

#4799 cleanups: remove NYI referencing #706
  src/dev/flang/ast/UnresolvedType.java
  src/dev/flang/fe/SourceModule.java
Labels: front end, cleanup

#4797 ast: Feature, add comment to _effects field
  src/dev/flang/ast/Feature.java
Labels: documentation, front end

#4802 build: Enable building `fuzion.ebnf` in a dir different than the source dir
  Makefile
  bin/ebnf.fz
Labels: bug, build infrastructure

#4781 Ast call, move generic size check to `get actual result type`
  src/dev/flang/ast/AbstractFeature.java
  src/dev/flang/ast/Call.java
Labels: front end, cleanup

#4792 fe: set _declaredOrInheritedFeatures in only one place
  src/dev/flang/fe/Module.java
  src/dev/flang/fe/SourceModule.java
  tests/argumentcount_negative/argumentcount_negative.fz.expected_err
Labels: front end, cleanup

#4794 fe: fix redefinition for features added to library features
  src/dev/flang/fe/SourceModule.java
  tests/reg_issue932/Makefile
  tests/reg_issue932/reg_issue932.fz
  tests/reg_issue932/reg_issue932.fz.expected_err
  tests/reg_issue932/reg_issue932.fz.expected_out
Labels: bug, front end

#4795 lib: cleanups in fraction
  modules/base/src/num/fraction.fz
Labels: base library, cleanup

#4796 fe: remove unused field _addedLate
  src/dev/flang/ast/Feature.java
  src/dev/flang/fe/SourceModule.java
Labels: front end, cleanup

#4808 dfa: Do not call `result()`in `Call.toString()`.
  src/dev/flang/fuir/analysis/dfa/Call.java
Labels: enhancement, dfa/monomorphization

#4798 fe: fix extension feature not found
  src/dev/flang/fe/SourceModule.java
  tests/partial_application/partial_application.fz
  tests/reg_issue4557/Makefile
  tests/reg_issue4557/reg_issue4557.fz
  tests/reg_issue4557/reg_issue4557.fz.expected_err
  tests/reg_issue4557/reg_issue4557.fz.expected_out
Labels: bug, front end

#4809 remove `__marker_for_make__` for fuzion rt
  Makefile
Labels: bug, build infrastructure

#4810 lib/tests: `redef fixed` => `fixed redef`
  modules/base/src/container/expanding_array.fz
  modules/base/src/os/process.fz
  tests/fallible/test_fallible.fz
  tests/reg_issue3619/reg_issue3619.fz
  tests/this_type/test_this_type.fz
Labels: base library, tests, cleanup

#4811 Dockerfile: install pcre-tools in builder
  Dockerfile
Labels: bug, build infrastructure, docker

#4672 lib: add `linear_effect`
  modules/base/src/concur/atomic.fz
  modules/base/src/effect.fz
  modules/base/src/mutate.fz
  tests/lib_fileio_mmap/mmap_test.fz.effect
  tests/lib_io_dir/lib_io_dir.fz.effect
  tests/lib_io_file/fileiotests.fz.effect
  tests/mod_lock_free_Map_threads/ctrie_threads.fz.effect
  tests/reg_issue4220/reg_issue4220.fz.expected_err
  tests/reg_issue4220/reg_issue4220.fz.expected_err_c
  tests/reg_issue4220/reg_issue4220.fz.expected_err_int
  tests/reg_issue4220/reg_issue4220.fz.expected_err_jvm
  tests/reg_issue4220/reg_issue4220.fz.expected_out
  tests/reg_issue4220/reg_issue4220.fz.expected_out_c
  tests/reg_issue4220/reg_issue4220.fz.expected_out_int
  tests/reg_issue4220/reg_issue4220.fz.expected_out_jvm
Labels: enhancement, base library

#4814 dockerfile: switch from termurin to ubuntu
  Dockerfile
Labels: build infrastructure

#4817 try fix question mark output in jenkins
  Dockerfile
Labels: bug, build infrastructure

#4816 ast: mark Call._select as private final
  src/dev/flang/ast/Call.java
  src/dev/flang/ast/Select.java
Labels: front end, cleanup

#4819 try fix locale in docker file
  Dockerfile
Labels: build infrastructure

#4820 nom: cleanups
  modules/base/src/Sequence.fz
  modules/nom/src/nom/multi.fz
  modules/nom/src/nom/sequences.fz
  modules/nom/src/nom/string_parsers.fz
Labels: base library, cleanup

#4824 fix spelling
  modules/base/src/effect.fz
Labels: cleanup

#4822 lib: cleanup new lines in option
  modules/base/src/option.fz
Labels: base library, cleanup

#4823 tests: cleanup, remove NYI: BUG:
  tests/reg_issue4348/reg_issue4348.fz
Labels: cleanup

#4827 lib: fix spelling
  modules/base/src/fuzion/sys/fileio.fz
Labels: base library, cleanup

#4825 dfa: SysArray._clazz, use FUIR.NO_CLAZZ instead of clazzAny
  src/dev/flang/fuir/analysis/dfa/Call.java
  src/dev/flang/fuir/analysis/dfa/SysArray.java
Labels: dfa/monomorphization, cleanup

#4833 fuir: simplify lookupCall(int cl)
  src/dev/flang/fuir/GeneratingFUIR.java
Labels: dfa/monomorphization, cleanup

#4832 fe: LibOut, relax check condition to allow native to have type params
  src/dev/flang/fe/LibraryOut.java
Labels: enhancement, front end

#4831 dfa: remove unused field
  src/dev/flang/fuir/analysis/dfa/SysArray.java
Labels: cleanup

#4830 time/instant: add precondition to `infix -`
  modules/base/src/time/instant.fz
Labels: base library, cleanup

#4835 Makefile: silence some `echo` commands
  Makefile
Labels: build infrastructure, cleanup

#4839 dfa: remove some unneeded code
  src/dev/flang/fuir/analysis/dfa/DFA.java
Labels: dfa/monomorphization, cleanup

#4840 fuir: change logic in lookup_
  src/dev/flang/fuir/GeneratingFUIR.java
Labels: dfa/monomorphization

#4841 lib: add `array.type.empty`
  modules/base/src/array.fz
Labels: base library

#4843 lib: cleanup native.fz
  modules/base/src/native.fz
  modules/base/src/time/now.fz
Labels: base library, cleanup

#4845 be/jvm: cleanup in AType
  src/dev/flang/be/jvm/classfile/ClassFileConstants.java
Labels: cleanup, jvm backend

#4844 time/date_time: remove UTC obsession
  modules/base/src/time/date_time.fz
  modules/base/src/time/now.fz
  tests/lib_time_date_time/lib_time_date_time.fz.expected_out
Labels: base library, cleanup
