Repository tokiwa-software/fuzion, pull requests merged in 2025-01, with the labels that each got.

#4515 fuir: move clazzFieldIsAdrOfValue to FUIR
  src/dev/flang/be/c/Intrinsics.java
  src/dev/flang/be/interpreter/Layout.java
  src/dev/flang/be/jvm/CodeGen.java
  src/dev/flang/be/jvm/JVM.java
  src/dev/flang/be/jvm/Types.java
  src/dev/flang/fuir/FUIR.java
  src/dev/flang/fuir/GeneratingFUIR.java
Labels: dfa/monomorphization, cleanup

#4534 fuir: move clazzIsChoice to FUIR
  src/dev/flang/be/c/C.java
  src/dev/flang/be/c/Intrinsics.java
  src/dev/flang/be/interpreter/Intrinsics.java
  src/dev/flang/be/jvm/Intrinsix.java
  src/dev/flang/fuir/FUIR.java
  src/dev/flang/fuir/GeneratingFUIR.java
  src/dev/flang/fuir/analysis/dfa/Call.java
  src/dev/flang/fuir/analysis/dfa/DFA.java
Labels: dfa/monomorphization, cleanup

#4535 fuir: move matchCaseIndex to FUIR
  src/dev/flang/fuir/FUIR.java
  src/dev/flang/fuir/GeneratingFUIR.java
Labels: dfa/monomorphization, cleanup

#4533 lib: add ffi convenience features: null, is_null
  include/fz.h
  include/shared.c
  modules/base/src/ffi.fz
Labels: enhancement, native

#4569 posix.c: remove telldir/seekdir which are not POSIX
  include/fz.h
  include/posix.c
  include/win.c
  modules/base/src/fuzion/sys/fileio.fz
  modules/base/src/io/dir/read.fz
Labels: base library, backend, cleanup

#4571 scripts: use any POSIX shell instead of bash
  bin/fz
  bin/fzjava
  bin/run_tests.sh
  bin/windows_install_boehm_gc.sh
  tests/_cur_dir.sh
  tests/_diff_err.sh
  tests/_strip_err.sh
Labels: cleanup

#4568 actions: fix linux workflow
  .github/workflows/apple.yml
  .github/workflows/linux.yml
  tests/check_simple_example_effect.sh
  tests/record_simple_example_effect.sh
Labels: build infrastructure

#4573 scripts: fix line.separator
  bin/fz
  bin/fzjava
Labels: bug, build infrastructure

#4574 makefile: Fix path to src directory for javadoc
  Makefile
Labels: bug, build infrastructure

#4575 native: `sys.process`, `sys.pipe` convert to native
  modules/base/src/fuzion/sys/pipe.fz
  modules/base/src/fuzion/sys/process.fz
  modules/base/src/os.fz
  modules/base/src/os/process.fz
  modules/base/src/os/processes.fz
  src/dev/flang/be/c/Intrinsics.java
  src/dev/flang/be/interpreter/ArrayData.java
  src/dev/flang/be/interpreter/Intrinsics.java
  src/dev/flang/be/jvm/runtime/Intrinsics.java
  src/dev/flang/be/jvm/runtime/Runtime.java
  src/dev/flang/fuir/analysis/dfa/DFA.java
  src/dev/flang/fuir/cfg/CFG.java
Labels: native

#4525 ast: fix field for result not added in nested match/if expr
  src/dev/flang/ast/If.java
  src/dev/flang/ast/Match.java
  tests/reg_issue4516/Makefile
  tests/reg_issue4516/reg_issue4516.fz
  tests/reg_issue4516/reg_issue4516.fz.expected_err
  tests/reg_issue4516/reg_issue4516.fz.expected_out
  tests/reg_issue4516_1/Makefile
  tests/reg_issue4516_1/reg_issue4516_1.fz
  tests/reg_issue4516_1/reg_issue4516_1.fz.expected_err
  tests/reg_issue4516_1/reg_issue4516_1.fz.expected_out
Labels: bug, front end

#4576 lock_free: fix file name, map.fz->Map.fz
  modules/lock_free/src/lock_free/Map.fz
Labels: cleanup

#4578 fuir: improve robustness of clazz_array_u8, etc.
  src/dev/flang/fuir/FUIR.java
Labels: enhancement, dfa/monomorphization

#4579 lib: change impl of Print_Handler and print_effect
  modules/base/src/concur/threads.fz
  modules/base/src/fuzion/std.fz
  modules/base/src/fuzion/sys/fileio.fz
  modules/base/src/fuzion/sys/stdin.fz
  modules/base/src/io/Read_Handler.fz
  modules/base/src/io/Read_Provider.fz
  modules/base/src/io/Write_Handler.fz
  modules/base/src/io/Write_Provider.fz
  modules/base/src/io/buffered/reader.fz
  modules/base/src/io/buffered/writer.fz
  modules/base/src/io/dir/read.fz
  modules/base/src/io/err.fz
  modules/base/src/io/file/use.fz
  modules/base/src/io/out.fz
  modules/base/src/io/print_effect.fz
  modules/base/src/io/stdin.fz
  modules/base/src/io/stdout.fz
  modules/base/src/net/channel.fz
  modules/base/src/net/connection.fz
  modules/base/src/os/process.fz
  tests/buffered_writer/ex_buffered_writer.fz
  tests/reg_issue4486/reg_issue4486.fz
Labels: base library, cleanup

#4584 be/jvm: cleanup, have only one place where `_fields.add` is called
  src/dev/flang/be/jvm/classfile/ClassFile.java
Labels: cleanup, jvm backend

#4582 be/c: add -CInclude, -CLink options
  src/dev/flang/be/c/C.java
  src/dev/flang/be/c/COptions.java
  src/dev/flang/tools/Fuzion.java
Labels: enhancement, C backend

#4586 tests: fix typo
  tests/outerNormalization/outerNormalization.fz
Labels: documentation, cleanup

#4587 be/jvm: assignField make arg order match ai.assignStatic
  src/dev/flang/be/jvm/CodeGen.java
  src/dev/flang/be/jvm/JVM.java
Labels: cleanup, jvm backend

#4589 be/jvm/interpreter: libraryLookup use only libraries explicity specified
  src/dev/flang/be/interpreter/Executor.java
  src/dev/flang/be/jvm/runtime/Runtime.java
Labels: interpreter backend, cleanup, jvm backend

#4588 Remove fuir field index
  bin/aspell.dict
  src/dev/flang/be/c/CNames.java
  src/dev/flang/be/interpreter/Interpreter.java
  src/dev/flang/be/interpreter/Intrinsics.java
  src/dev/flang/be/interpreter/JavaInterface.java
  src/dev/flang/be/interpreter/Layout.java
  src/dev/flang/be/jvm/Names.java
  src/dev/flang/fuir/Clazz.java
  src/dev/flang/fuir/FUIR.java
  src/dev/flang/fuir/GeneratingFUIR.java
Labels: dfa/monomorphization, backend, cleanup

#4593 makefile: do `rm -rf $(@D)` when rebuilding modules
  Makefile
Labels: enhancement, build infrastructure

#4596 be/int: Layout, do not use specialclazz pointer
  src/dev/flang/be/interpreter/Interpreter.java
  src/dev/flang/be/interpreter/Layout.java
Labels: enhancement, interpreter backend

#4597 fuir: remove methods lookup, recordAbstractMissing
  src/dev/flang/fuir/FUIR.java
  src/dev/flang/fuir/GeneratingFUIR.java
  src/dev/flang/fuir/analysis/dfa/DFA.java
  src/dev/flang/opt/Optimizer.java
Labels: dfa/monomorphization, cleanup

#4595 lib: buffered.writer, use LM of `buffered`
  modules/base/src/io/buffered/writer.fz
Labels: enhancement, base library

#4598 fuir: remove inlineArrayElementClazz from GeneratingFUIR
  src/dev/flang/fuir/FUIR.java
  src/dev/flang/fuir/GeneratingFUIR.java
Labels: dfa/monomorphization, cleanup

#4600 readme: update example
  README.md
Labels: bug, documentation

#4599 dfa: error when replacing effect that is not installed
  src/dev/flang/fuir/analysis/dfa/Call.java
  src/dev/flang/fuir/analysis/dfa/DFA.java
  tests/reg_issue4592/Makefile
  tests/reg_issue4592/reg_issue4592.fz
  tests/reg_issue4592/reg_issue4592.fz.expected_err
  tests/reg_issue4592/reg_issue4592.fz.expected_out
Labels: bug, dfa/monomorphization

#4601 fuir: remove lookupCall with 2 args
  src/dev/flang/fuir/FUIR.java
  src/dev/flang/fuir/GeneratingFUIR.java
Labels: dfa/monomorphization, cleanup

#4604 tests: add test #4250
  tests/reg_issue4250/Makefile
  tests/reg_issue4250/reg_issue4250.fz
  tests/reg_issue4250/reg_issue4250.fz.expected_err
  tests/reg_issue4250/reg_issue4250.fz.expected_out
Labels: bug, tests

#4603 naming: use <name>Count instead of Num<names>
  src/dev/flang/be/c/C.java
  src/dev/flang/be/c/CTypes.java
  src/dev/flang/be/c/Intrinsics.java
  src/dev/flang/be/interpreter/ChoiceIdAsRef.java
  src/dev/flang/be/interpreter/Layout.java
  src/dev/flang/be/jvm/Choices.java
  src/dev/flang/be/jvm/JVM.java
  src/dev/flang/be/jvm/Names.java
  src/dev/flang/fuir/FUIR.java
  src/dev/flang/fuir/GeneratingFUIR.java
Labels: dfa/monomorphization, cleanup

#4606 ast: InlineArray.propagateExpectedType fix check condition
  src/dev/flang/ast/InlineArray.java
  tests/reg_issue4424/Makefile
  tests/reg_issue4424/reg_issue4424.fz
  tests/reg_issue4424/reg_issue4424.fz.expected_err
  tests/reg_issue4424/reg_issue4424.fz.expected_out
Labels: bug, front end

#4607 ast: fix strange errors reported
  src/dev/flang/ast/AbstractAssign.java
  tests/reg_issue4479/Makefile
  tests/reg_issue4479/reg_issue4479.fz
  tests/reg_issue4479/reg_issue4479.fz.expected_err
  tests/reg_issue4479/reg_issue4479.fz.expected_out
Labels: bug, front end

#4610 ast: fix crash when failing to infer generic argument
  src/dev/flang/ast/AbstractType.java
  tests/reg_issue4542/Makefile
  tests/reg_issue4542/reg_issue4542.fz
  tests/reg_issue4542/reg_issue4542.fz.expected_err
  tests/reg_issue4542/reg_issue4542.fz.expected_out
Labels: bug, front end

#4590 lib: change io.out/io.err to ref features
  modules/base/src/fuzion/std.fz
  modules/base/src/io/Err.fz
  modules/base/src/io/Out.fz
  modules/base/src/io/print_effect.fz
  src/dev/flang/be/jvm/Intrinsix.java
  src/dev/flang/be/jvm/runtime/Runtime.java
  tests/asParsedType/test_asParsedType.fz
  tests/asParsedType/test_asParsedType.fz.expected_out
  tests/asParsedType_negative/test_asParsedType_negative.fz
  tests/asParsedType_negative/test_asParsedType_negative.fz.expected_err
  tests/assignments/assignments.fz.effect
  tests/atomic/test_atomic.fz.effect
  tests/buffered_writer/ex_buffered_writer.fz
  tests/hello/HelloWorld.fz.effect
  tests/i18n_default_test/i18n_default_test.fz.effect
  tests/inherit_postcondition/inherit_postcondition.fz
  tests/inherit_postcondition/module_src/mod.fz
  tests/lib_concur_sync/lib_concur_sync.fz.effect
  tests/lib_fileio_mmap/mmap_test.fz.effect
  tests/lib_io_dir/lib_io_dir.fz.effect
  tests/lib_io_file/fileiotests.fz.effect
  tests/lib_memoize/lib_memoize.fz.effect
  tests/mod_lock_free_Map/ctrie_test.fz.effect
  tests/mod_lock_free_Map_threads/ctrie_threads.fz.effect
  tests/reg_issue118/issue118.fz.expected_err
  tests/reg_issue1741/reg_issue1741.fz.expected_err
  tests/reg_issue3769/reg_issue3769.fz
  tests/reg_issue3769/reg_issue3769.fz.expected_err
  tests/reg_issue4220/reg_issue4220.fz
Labels: enhancement, base library

#4612 ast: check for duplicate feature when adding type parameter
  src/dev/flang/ast/Feature.java
  tests/reg_issue4540/Makefile
  tests/reg_issue4540/reg_issue4540.fz
  tests/reg_issue4540/reg_issue4540.fz.expected_err
  tests/reg_issue4540/reg_issue4540.fz.expected_out
Labels: bug, front end

#4614 tests: add reg test #4518
  tests/reg_issue4518/Makefile
  tests/reg_issue4518/reg_issue4518.fz
  tests/reg_issue4518/reg_issue4518.fz.expected_err
  tests/reg_issue4518/reg_issue4518.fz.expected_out
Labels: bug, tests

#4613 fe: fix index out of bounds in SourceModule.inScope
  src/dev/flang/fe/SourceModule.java
  tests/reg_issue4529/Makefile
  tests/reg_issue4529/reg_issue4529.fz
  tests/reg_issue4529/reg_issue4529.fz.expected_err
  tests/reg_issue4529/reg_issue4529.fz.expected_out
Labels: bug, front end

#4616 ast: partial application: do not wrap function argument into a lamba, fix #4609
  src/dev/flang/ast/ParsedCall.java
  tests/catch_postcondition/catch_postcondition.fz.expected_err_int
  tests/effect_installed_negative/test_effect_neg.fz.expected_err
  tests/mod_lock_free_Map/ctrie_test.fz.effect
  tests/reg_issue2231/reg_issue2231.fz.expected_err_int
  tests/reg_issue4549/reg_issue4549.fz.expected_err
  tests/reg_issue4609/Makefile
  tests/reg_issue4609/reg_issue4609.fz
  tests/reg_issue4609/reg_issue4609.fz.expected_err_c
  tests/reg_issue4609/reg_issue4609.fz.expected_err_int
  tests/reg_issue4609/reg_issue4609.fz.expected_err_jvm
  tests/reg_issue4609/reg_issue4609.fz.expected_out_c
  tests/reg_issue4609/reg_issue4609.fz.expected_out_int
  tests/reg_issue4609/reg_issue4609.fz.expected_out_jvm
Labels: bug, enhancement, front end, performance issue

#4623 release 0.091
  release_notes.md
  version.txt
Labels: build infrastructure

#4618 ast: constraintAssignableFrom return false for void unless constraint…
  src/dev/flang/ast/AbstractType.java
  tests/reg_issue4480/Makefile
  tests/reg_issue4480/reg_issue4480.fz
  tests/reg_issue4480/reg_issue4480.fz.expected_err
  tests/reg_issue4480/reg_issue4480.fz.expected_out
Labels: bug, front end

#4615 fe: re-enable partial application for expr in parentheses
  src/dev/flang/ast/ParsedCall.java
  src/dev/flang/ast/ParsedOperatorCall.java
  src/dev/flang/parser/Parser.java
  tests/reg_issue4503/Makefile
  tests/reg_issue4503/reg_issue4503.fz
  tests/reg_issue4503/reg_issue4503.fz.expected_err
  tests/reg_issue4503/reg_issue4503.fz.expected_out
Labels: bug, front end

#4625 ast: fix calling type on partial not resulting in error
  src/dev/flang/ast/Partial.java
  tests/reg_issue4621/Makefile
  tests/reg_issue4621/reg_issue4621.fz
  tests/reg_issue4621/reg_issue4621.fz.expected_err
  tests/reg_issue4621/reg_issue4621.fz.expected_out
Labels: bug, front end

#4627 remove uses of ast.Context anywhere but `ast`
  src/dev/flang/ast/AbstractAssign.java
  src/dev/flang/ast/AbstractCurrent.java
  src/dev/flang/ast/AbstractLambda.java
  src/dev/flang/ast/AbstractType.java
  src/dev/flang/ast/Assign.java
  src/dev/flang/ast/Block.java
  src/dev/flang/ast/Call.java
  src/dev/flang/ast/Cond.java
  src/dev/flang/ast/Context.java
  src/dev/flang/ast/Destructure.java
  src/dev/flang/ast/DotType.java
  src/dev/flang/ast/Expr.java
  src/dev/flang/ast/Feature.java
  src/dev/flang/ast/Function.java
  src/dev/flang/ast/Generic.java
  src/dev/flang/ast/If.java
  src/dev/flang/ast/Impl.java
  src/dev/flang/ast/InlineArray.java
  src/dev/flang/ast/Match.java
  src/dev/flang/ast/NumLiteral.java
  src/dev/flang/ast/ParsedCall.java
  src/dev/flang/ast/Partial.java
  src/dev/flang/ast/SrcModule.java
  src/dev/flang/ast/Tag.java
  src/dev/flang/ast/This.java
  src/dev/flang/fe/LibraryFeature.java
  src/dev/flang/fe/SourceModule.java
  src/dev/flang/fuir/Clazz.java
  src/dev/flang/fuir/GeneratingFUIR.java
Labels: front end, dfa/monomorphization, cleanup

#4633 LibraryOut: fix typo in verbose message of constructor
  src/dev/flang/fe/LibraryOut.java
Labels: front end

#4639 mir: `addCode` remove unused argument
  src/dev/flang/mir/MIR.java
Labels: cleanup

#4640 fuir: toStack, code simplifications
  src/dev/flang/fuir/GeneratingFUIR.java
Labels: cleanup

#4648 fuir: fix instability in clazz._id
  src/dev/flang/fuir/Clazz.java
  src/dev/flang/fuir/GeneratingFUIR.java
Labels: bug, dfa/monomorphization

#4652 ast: fix Context.exterior and comparison of type parameters
  src/dev/flang/ast/Context.java
  tests/reg_issue4628/Makefile
  tests/reg_issue4628/reg_issue4628.fz
  tests/reg_issue4628/reg_issue4628.fz.expected_err
  tests/reg_issue4628/reg_issue4628.fz.expected_out
Labels: bug, front end

#4643 fuir: do not create new clazzes when lookupDone==true
  src/dev/flang/be/interpreter/Interpreter.java
  src/dev/flang/fuir/Clazz.java
  src/dev/flang/fuir/GeneratingFUIR.java
  src/dev/flang/fuir/analysis/TailCall.java
Labels: dfa/monomorphization, cleanup

#4660 fe: fix soundness issue in checkLegalQualThisType
  modules/base/src/container/Set.fz
  modules/base/src/container/ps_set.fz
  modules/base/src/interval.fz
  src/dev/flang/fe/SourceModule.java
Labels: bug, front end

#4663 ast: fix resolving of unresolved type universe
  src/dev/flang/ast/Call.java
  src/dev/flang/ast/Universe.java
  src/dev/flang/ast/UnresolvedType.java
  tests/reg_issue3973/Makefile
  tests/reg_issue3973/reg_issue3973.fz
  tests/reg_issue3973/reg_issue3973.fz.expected_err
  tests/reg_issue3973/reg_issue3973.fz.expected_out
Labels: bug, front end

#4664 fuir: cache result field
  src/dev/flang/fuir/Clazz.java
Labels: dfa/monomorphization

#4666 fuir: record which sites and code where used by DFA
  src/dev/flang/fuir/GeneratingFUIR.java
Labels: dfa/monomorphization

#4669 ast: improve inference of generic for Lazy
  src/dev/flang/ast/Call.java
  tests/reg_issue4548/Makefile
  tests/reg_issue4548/reg_issue4548.fz
  tests/reg_issue4548/reg_issue4548.fz.expected_err
  tests/reg_issue4548/reg_issue4548.fz.expected_out
Labels: bug, front end

#4671 lib: io.buffered.writer do not instate to create buffer
  modules/base/src/io/buffered/writer.fz
Labels: base library, cleanup

#4673 tests: add regression test for issue #2301
  tests/reg_issue2301/Makefile
  tests/reg_issue2301/reg_issue2301.fz
  tests/reg_issue2301/reg_issue2301.fz.expected_err
  tests/reg_issue2301/reg_issue2301.fz.expected_out
Labels: tests

#4677 lib: uncomment commented code without NYI
  modules/base/src/i64.fz
  modules/base/src/u64.fz
Labels: base library, cleanup

#4678 parser: OpExpr, change semantics to handle `x?? && y??`
  src/dev/flang/parser/OpExpr.java
  tests/reg_issue4632/Makefile
  tests/reg_issue4632/reg_issue4632.fz
  tests/reg_issue4632/reg_issue4632.fz.expected_err
  tests/reg_issue4632/reg_issue4632.fz.expected_out
Labels: bug, parser

#4682 lib: cleanup outdated NYI
  modules/base/src/array.fz
  modules/base/src/container/Set.fz
  modules/base/src/memoize.fz
  modules/base/src/num/wrap_around.fz
  modules/lock_free/src/lock_free/Sieve_Cache.fz
Labels: base library, cleanup

#4675 lib: orderable provide implementation for type.equality
  modules/base/src/property/orderable.fz
Labels: enhancement, base library

#4688 ast: fix applyTypePars for this-types
  src/dev/flang/ast/AbstractType.java
  tests/mix_inheritance_and_outer/Makefile
  tests/mix_inheritance_and_outer/mix_inheritance_and_outer.fz.expected_err
  tests/mix_inheritance_and_outer/mix_inheritance_and_outer.fz.expected_out
Labels: bug, front end

#4692 lib: fix performance issue in `expanding_array`
  modules/base/src/container/expanding_array.fz
Labels: bug, base library, performance issue

#4689 Fix partial application when calling infix operator, fix #4687
  src/dev/flang/ast/Call.java
  src/dev/flang/ast/ParsedCall.java
  tests/partial_application/partial_application.fz
  tests/partial_application/partial_application.fz.expected_out
  tests/partial_application_negative/partial_application_negative.fz.expected_err
  tests/reg_issue4549/reg_issue4549.fz.expected_err
Labels: bug, enhancement, front end

#4697 tests: add regression test #4248
  tests/reg_issue4248/Makefile
  tests/reg_issue4248/reg_issue4248.fz
  tests/reg_issue4248/reg_issue4248.fz.expected_err
  tests/reg_issue4248/reg_issue4248.fz.expected_out
Labels: bug

#4699 ast: cleanups in Call/ParsedCall
  src/dev/flang/ast/Call.java
  src/dev/flang/ast/ParsedCall.java
Labels: cleanup
